### ISSUE TITLE
ResolutionImpossible: kappa==0.6.0 on pkgs.python36

### ISSUE THREAD

**Issue by bb010g** [DavHau/mach-nix#105]
```nix
let
  mach-nix-src-boot = builtins.fetchGit {
    url = "https://github.com/DavHau/mach-nix/";
    ref = "refs/tags/2.3.0";
  };
  mach-nix-boot = import mach-nix-src-boot;
  pkgs-boot = mach-nix-boot.nixpkgs;
  mach-nix-src = let
    src = mach-nix-src-boot;
    patches = [
      (builtins.toFile "mach-nix-dump.patch" ''
--- a/mach_nix/generate.py
+++ b/mach_nix/generate.py
@@ -1,6 +1,7 @@
 import json
 import os
 import sys
+import traceback
 from os.path import dirname
 from pprint import pformat
 from typing import List
@@ -88,6 +89,7 @@ def handle_resolution_impossible(exc: ResolutionImpossible, reqs_str, providers_
         f"The requirements which caused the error:"
         f"{causes_str}\n",
         file=sys.stderr)
+    traceback.print_exc(file=sys.stderr)
 
 
 if __name__ == "__main__":
      '')
    ];
  in if patches == [ ] then src else pkgs-boot.applyPatches {
    name = "match-nix-src-patched";
    inherit src patches;
  };
  mach-nix = import mach-nix-src;
  pkgs = mach-nix.nixpkgs;
  machNixFile-src = "${mach-nix-src}/mach_nix/nix/mach.nix";
  machNixFile = import machNixFile-src;
in machNixFile {
  python = pkgs.python36; # failure
  # python = pkgs.python37; # success
  requirements = ''
    kappa==0.6.0
  '';
}
```

```
bb010g ~/.../python/example-nixpkgs-dev-env % nix-build --show-trace -k mach-nix-mwe.nix
these derivations will be built:
  /nix/store/s2dcbcbfgbqyfps1lh920br4ih5qnzy0-mach_nix_file.drv
building '/nix/store/s2dcbcbfgbqyfps1lh920br4ih5qnzy0-mach_nix_file.drv'...

Some requirements could not be resolved.
Top level requirements:
  kappa==0.6.0
Providers:
  {'_default': 'wheel,sdist,nixpkgs',
   'gdal': 'nixpkgs',
   'pip': 'nixpkgs',
   'setupmeta': 'wheel',
   'setuptools': 'nixpkgs',
   'wheel': 'nixpkgs,sdist'}
Mach-nix version: 2.3.0
Python: 3.6.11
Cause: Requirements conflict: Requirement.parse('kappa==0.6.0')
The requirements which caused the error:
  kappa==0.6.0

Traceback (most recent call last):
  File "/nix/store/h7sh37qqjhyw7bp55csg88yic3ymvk82-python3-3.7.8-env/lib/python3.7/site-packages/resolvelib/resolvers.py", line 185, in
 _merge_into_criterion
    crit = self.state.criteria[name]
KeyError: 'kappa'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/h7sh37qqjhyw7bp55csg88yic3ymvk82-python3-3.7.8-env/lib/python3.7/site-packages/resolvelib/resolvers.py", line 280, in
 resolve
    name, crit = self._merge_into_criterion(r, parent=None)
  File "/nix/store/h7sh37qqjhyw7bp55csg88yic3ymvk82-python3-3.7.8-env/lib/python3.7/site-packages/resolvelib/resolvers.py", line 187, in
 _merge_into_criterion
    crit = Criterion.from_requirement(self._p, requirement, parent)
  File "/nix/store/h7sh37qqjhyw7bp55csg88yic3ymvk82-python3-3.7.8-env/lib/python3.7/site-packages/resolvelib/resolvers.py", line 87, in
from_requirement
    raise RequirementsConflicted(criterion)
resolvelib.resolvers.RequirementsConflicted: Requirements conflict: Requirement.parse('kappa==0.6.0')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/5daxyvrpm6b3l3s8ag1cf9wysifzaciw-yky9dfn076mgcc359aaj46b7vz0i3xv7-match-nix-src-patched/mach_nix/generate.py", line 6
4, in main
    expr = generator.generate(reqs)
  File "/nix/store/5daxyvrpm6b3l3s8ag1cf9wysifzaciw-yky9dfn076mgcc359aaj46b7vz0i3xv7-match-nix-src-patched/mach_nix/generators/overides_
generator.py", line 34, in generate
    pkgs = self.resolver.resolve(reqs)
  File "/nix/store/5daxyvrpm6b3l3s8ag1cf9wysifzaciw-yky9dfn076mgcc359aaj46b7vz0i3xv7-match-nix-src-patched/mach_nix/resolver/resolvelib_
resolver.py", line 63, in resolve
    result = resolvelib.Resolver(Provider(self.nixpkgs, self.deps_provider), reporter).resolve(reqs, max_rounds=1000)
  File "/nix/store/h7sh37qqjhyw7bp55csg88yic3ymvk82-python3-3.7.8-env/lib/python3.7/site-packages/resolvelib/resolvers.py", line 413, in
 resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/nix/store/h7sh37qqjhyw7bp55csg88yic3ymvk82-python3-3.7.8-env/lib/python3.7/site-packages/resolvelib/resolvers.py", line 282, in
 resolve
    raise ResolutionImpossible(e.criterion.information)
resolvelib.resolvers.ResolutionImpossible: [RequirementInformation(requirement=Requirement.parse('kappa==0.6.0'), parent=None)]
builder for '/nix/store/s2dcbcbfgbqyfps1lh920br4ih5qnzy0-mach_nix_file.drv' failed with exit code 1
error: build of '/nix/store/s2dcbcbfgbqyfps1lh920br4ih5qnzy0-mach_nix_file.drv' failed
(100) bb010g ~/.../python/example-nixpkgs-dev-env %
```

Chasing stacktraces around hasn't really gone anywhere. If you let the requirement float (`kappa`), `kappa==0.3.1` is picked. A requirement of `kappa>0.3.1` fails.

**Comment by DavHau** [comment]
Interesting. I'll take a deeper look into it as soon as i got some time.

kappa 0.6.0 seems to be installable via pip and pyhton3.6.
BTW, you can always trigger the resolver manually without nix by using ./debug/debug.py .

Es you noticed resolvelib doesn't really have a nice reporting interface right now. The upstream maintainer is working on that.

**Comment by bb010g** [comment]
Any luck on why this is happening?

**Comment by DavHau** [comment]
Sorry. Somehow I had in my mind, that i already answered. I might have forgotten to click the button.
There are 2 problems with kappa:
1. Their wheel release is flagged for python 2. You can [see that on pypi](https://pypi.org/project/kappa/0.6.0/#files)  
  Not sure if this intentional or by mistake. Neither pip nor mach-nix chose the wheel release when you are on python 3
2. The Sdist release's dependencies could not be analyzed for python 3.5/3.6. Using those python interpreters the setup.py raised the following error:
```
Traceback (most recent call last):
  File "<string>", line 5, in <module>
  File "setup.py", line 54, in <module>
    run_setup()
  File "setup.py", line 22, in run_setup
    long_description=open_file('README.rst').read(),
  File "/nix/store/67032xvbrqcrbr9jn12gmb9rfymknchq-python3-3.6.9/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 2339: ordinal not in range(128)
```

This error did not happen for python 3.7/3.8. If you have an idea on how to fix that, let me know and I can try to include the fix into the crawler.

In the meantime, might this be sufficient for you?
```
with builtins;
let
  mach-nix = import (builtins.fetchGit {
    url = "https://github.com/DavHau/mach-nix/";
    rev = "2ee3786b06ab2c3d7f46c2a7cae3f9c3fa0dc0c9";
  });
  kappa = mach-nix.buildPythonPackage rec {
    src = mach-nix.fetchPypiSdist pname version;
    pname = "kappa";
    version = "0.6.0";
    python = "python36";
    requirements = ''
      PyYAML>=3.11
      boto3>=1.2.3
      click>=5.1
      placebo>=0.8.1
    '';
  };
in
kappa
```

**Comment by bb010g** [comment]
That feels like Nixpkgs's pre-`LANG = "C.UTF-8"` Python problems? https://github.com/NixOS/nixpkgs/pull/55826

**Comment by bb010g** [comment]
Relevant diff: https://github.com/garnaat/kappa/compare/0.3.1..0.4.0

0.4.0's `README.rst` starts using Unicode box drawing characters at position 2339.

**Comment by DavHau** [comment]
Nice, `LANG = "C.UTF-8"` that seems to fix the problem. I'll put that into the crawler

**Comment by DavHau** [comment]
I added the missing variable to the crawler and deleted ~ 188K DB entries which had the same error. It might take a few days for the crawler to re-crawl those releases.

**Comment by DavHau** [comment]
With this fix and a few other improvements I just added, you can build kappa now like this:
```nix
let
  mach-nix = import (builtins.fetchGit {
    url = "https://github.com/DavHau/mach-nix/";
    rev = "469891f8d0959aa97b3a0e3566a70488caeac499";
  });
  kappa = mach-nix.buildPythonPackage (mach-nix.fetchPypiSdist "kappa" "0.6.0");
in
kappa
```
