### ISSUE TITLE
enum34

### ISSUE THREAD

**Issue by tfmoraes** [DavHau/mach-nix#108]
Some python packages depends on enum34 but enum34 is not available to newer python versions. An example of python packages that depends on enum34 is plaidml. See this example:

```nix
let
  mach-nix = import (builtins.fetchGit {
    url = "https://github.com/DavHau/mach-nix/";
    ref = "refs/tags/2.3.0";
  });
in
mach-nix.mkPythonShell {
  requirements = ''
    plaidml-keras
  '';
}
```

Unfortunately, I was not able to manage mach-nix to install enum34. It fails with this error:

```
building '/nix/store/wzsfzfbp5rr19a9fbyilf5j6s6xbq9rs-mach_nix_file.drv'...

### Resolved Dependencies ###

plaidml-keras - 0.7.0 - wheel
├── keras - 2.2.4 - wheel
│   ├── h5py - 2.10.0 - wheel
│   │   ├── numpy - 1.19.1 - wheel
│   │   └── six - 1.15.0 - wheel
│   ├── keras-applications - 1.0.8 - wheel
│   │   ├── h5py - 2.10.0 - wheel
│   │   │   ├── numpy - 1.19.1 - wheel
│   │   │   └── six - 1.15.0 - wheel
│   │   └── numpy - 1.19.1 - wheel
│   ├── keras-preprocessing - 1.1.2 - wheel
│   │   ├── numpy - 1.19.1 - wheel
│   │   └── six - 1.15.0 - wheel
│   ├── numpy - 1.19.1 - wheel
│   ├── pyyaml - 5.3.1 - sdist
│   ├── scipy - 1.5.2 - wheel
│   │   └── numpy - 1.19.1 - wheel
│   └── six - 1.15.0 - wheel
├── plaidml - 0.7.0 - wheel
│   ├── cffi - 1.14.2 - wheel
│   │   └── pycparser - 2.20 - wheel
│   ├── enum34 - 1.1.10 - wheel
│   ├── numpy - 1.19.1 - wheel
│   └── six - 1.15.0 - wheel
└── six - 1.15.0 - wheel

these derivations will be built:
  /nix/store/0bac04c0mdzw4a12xlysh23spcf6xvgh-python3.8-pycparser-2.20.drv
  /nix/store/4iawfqdkj3d2662hswviylh4if3sqgr4-python3.8-six-1.15.0.drv
  /nix/store/6kldfiqny7v0ccq17rj45b10pq24pqbn-python3.8-numpy-1.19.1.drv
  /nix/store/gbqr8n832icf2hxg5ym31kwknywgd76y-Keras_Preprocessing-1.1.2-py2.py3-none-any.whl.drv
  /nix/store/0j5v3jy1yb1cxdpsdbqk6c24c9bai4v7-python3.8-keras-preprocessing-1.1.2.drv
  /nix/store/42rc12bc6k1zdgxpyad7kvrlgmnznyp3-python3.8-enum34-1.1.10.drv
  /nix/store/l578c88j8y97zyv943zdk2ncngcgpc4x-python3.8-cffi-1.14.2.drv
  /nix/store/1224pv136y3wpw183ij3b003qzpliv58-python3.8-plaidml-0.7.0.drv
  /nix/store/2805caqz6w1k6d1mkrldwzyssf432iyh-python3.8-scipy-1.5.2.drv
  /nix/store/al8qnpzzjq86c4sijhwk343xafa5633c-python3.8-h5py-2.10.0.drv
  /nix/store/59x06j316cfadmi9358b5qddmw8cms3k-python3.8-keras-applications-1.0.8.drv
  /nix/store/y1dd45yd5fypdplc5w42pq9bax6pcjxw-python3.8-keras-2.2.4.drv
  /nix/store/rjrhjgwq6gnhj9sll58pn30vimrc2rv6-python3.8-plaidml-keras-0.7.0.drv
  /nix/store/ncwlrj5wxiv1zngs9i50jpz4hg0mlg1h-python3-3.8.5-env.drv
building '/nix/store/42rc12bc6k1zdgxpyad7kvrlgmnznyp3-python3.8-enum34-1.1.10.drv'...
building '/nix/store/6kldfiqny7v0ccq17rj45b10pq24pqbn-python3.8-numpy-1.19.1.drv'...
building '/nix/store/0bac04c0mdzw4a12xlysh23spcf6xvgh-python3.8-pycparser-2.20.drv'...
building '/nix/store/4iawfqdkj3d2662hswviylh4if3sqgr4-python3.8-six-1.15.0.drv'...
building '/nix/store/gbqr8n832icf2hxg5ym31kwknywgd76y-Keras_Preprocessing-1.1.2-py2.py3-none-any.whl.drv'...
Sourcing python-recompile-bytecode-hook.sh
Sourcing python-remove-tests-dir-hook
Sourcing python-catch-conflicts-hook.sh
Sourcing python-remove-bin-bytecode-hook.sh
Sourcing wheel setup hook
Using wheelUnpackPhase
Sourcing pip-install-hook
Using pipInstallPhase
Sourcing python-imports-check-hook.sh
Using pythonImportsCheckPhase
Sourcing python-namespaces-hook
Sourcing python-recompile-bytecode-hook.sh
Sourcing python-remove-tests-dir-hook
Sourcing python-recompile-bytecode-hook.sh
Sourcing python-remove-tests-dir-hook
Sourcing python-catch-conflicts-hook.sh
Sourcing python-remove-bin-bytecode-hook.sh
Sourcing wheel setup hook
Using wheelUnpackPhase
Sourcing python-catch-conflicts-hook.sh
Sourcing python-remove-bin-bytecode-hook.sh
Sourcing pip-install-hook
Sourcing wheel setup hook
Using pipInstallPhase
Using wheelUnpackPhase
Sourcing pip-install-hook
Sourcing python-imports-check-hook.sh
Using pythonImportsCheckPhase
Using pipInstallPhase
Sourcing python-namespaces-hook
Sourcing python-imports-check-hook.sh
Using pythonImportsCheckPhase
Sourcing python-namespaces-hook
Sourcing python-recompile-bytecode-hook.sh
Sourcing python-remove-tests-dir-hook
Sourcing python-catch-conflicts-hook.sh
Sourcing python-remove-bin-bytecode-hook.sh
Sourcing wheel setup hook
Using wheelUnpackPhase
Sourcing pip-install-hook
Using pipInstallPhase
Sourcing python-imports-check-hook.sh
Using pythonImportsCheckPhase
Sourcing python-namespaces-hook
unpacking sources
Executing wheelUnpackPhase
Finished executing wheelUnpackPhase
patching sources
configuring
no configure script, doing nothing
building
no Makefile, doing nothing
installing
Executing pipInstallPhase
/build/dist /build
unpacking sources
Executing wheelUnpackPhase
Finished executing wheelUnpackPhase
patching sources
unpacking sources
Executing wheelUnpackPhase
configuring
unpacking sources
Executing wheelUnpackPhase
Finished executing wheelUnpackPhase
no configure script, doing nothing
patching sources
building
no Makefile, doing nothing
configuring
installing
Executing pipInstallPhase
/build/dist /build
no configure script, doing nothing
building
no Makefile, doing nothing
installing
Executing pipInstallPhase
/build/dist /build
Finished executing wheelUnpackPhase
patching sources
configuring
no configure script, doing nothing
building
no Makefile, doing nothing
installing
Executing pipInstallPhase
/build/dist /build
Processing ./pycparser-2.20-py2.py3-none-any.whl
Processing ./numpy-1.19.1-cp38-cp38-manylinux2010_x86_64.whl
Processing ./enum34-1.1.10-py3-none-any.whl
Processing ./six-1.15.0-py2.py3-none-any.whl
Installing collected packages: pycparser
Installing collected packages: enum34
Installing collected packages: six
Successfully installed enum34-1.1.10
Successfully installed six-1.15.0
/build
/build
Finished executing pipInstallPhase
Finished executing pipInstallPhase
post-installation fixup
post-installation fixup
shrinking RPATHs of ELF executables and libraries in /nix/store/2n2wn711g0zkn426m95g3qfxzja9fvjn-python3.8-enum34-1.1.10
shrinking RPATHs of ELF executables and libraries in /nix/store/n4zhi9fx42390ba2f9hhvh6cf3a6b6ng-python3.8-six-1.15.0
patching script interpreter paths in /nix/store/n4zhi9fx42390ba2f9hhvh6cf3a6b6ng-python3.8-six-1.15.0
patching script interpreter paths in /nix/store/2n2wn711g0zkn426m95g3qfxzja9fvjn-python3.8-enum34-1.1.10
checking for references to /build/ in /nix/store/2n2wn711g0zkn426m95g3qfxzja9fvjn-python3.8-enum34-1.1.10...
checking for references to /build/ in /nix/store/n4zhi9fx42390ba2f9hhvh6cf3a6b6ng-python3.8-six-1.15.0...
Executing pythonRemoveTestsDir
Executing pythonRemoveTestsDir
Finished executing pythonRemoveTestsDir
pythonCatchConflictsPhase
Finished executing pythonRemoveTestsDir
pythonCatchConflictsPhase
Successfully installed pycparser-2.20
Traceback (most recent call last):
  File "/nix/store/q2zpnf017gccs9w9mb0ikdqhkf0k5v82-catch_conflicts.py", line 1, in <module>
    import pkg_resources
  File "/nix/store/rpgik653k5r1y9526nm2cgl6514rdjgx-python3.8-setuptools-47.3.1/lib/python3.8/site-packages/pkg_resources/__init__.py", line 24, in <module>
    import re
  File "/nix/store/fjgnz0xfl04hsblsi4ym5y5akfh6mlmy-python3-3.8.5/lib/python3.8/re.py", line 145, in <module>
    class RegexFlag(enum.IntFlag):
AttributeError: module 'enum' has no attribute 'IntFlag'
/build
Finished executing pipInstallPhase
post-installation fixup
shrinking RPATHs of ELF executables and libraries in /nix/store/8ffpsn7k69i94yhss6bnk70wqwsz2xzr-python3.8-pycparser-2.20
patching script interpreter paths in /nix/store/8ffpsn7k69i94yhss6bnk70wqwsz2xzr-python3.8-pycparser-2.20
builder for '/nix/store/42rc12bc6k1zdgxpyad7kvrlgmnznyp3-python3.8-enum34-1.1.10.drv' failed with exit code 1
cannot build derivation '/nix/store/ncwlrj5wxiv1zngs9i50jpz4hg0mlg1h-python3-3.8.5-env.drv': 1 dependencies couldn't be built
error: build of '/nix/store/ncwlrj5wxiv1zngs9i50jpz4hg0mlg1h-python3-3.8.5-env.drv' failed
```

Is it possible to avoid mach-nix to try to install enum34?

**Comment by DavHau** [comment]
It makes no sense to install enum34 on any python version > 3.3 since enum34 is a backport lib  for python versions older than 3.4.

Therefore plaidml and plaidml-keras should introduce a constraint that limits the enum34 requirement to older python versions.

In pip,  enum34 can be installed, but it will just be ignored during runtime since it clashes with the builtin enum library.
Try installing it and then execute `print(enum.__file__)`.

The reason the installation of enum34 crashes under nix is probably because one of the build phases depends on enum and clashing names produce a different result than in pip.

But since enum34 doesn't really belong here, I suggest to report/fix it upstream. Until it is fixed, you can hack your way around like this:
```nix
mach-nix.mkPythonShell {
  requirements = ''
    plaidml-keras
  '';

  _.enum34.phases = "installPhase";
  _.enum34.installPhase = "mkdir $out";

  _.plaidml.pipInstallFlags = "--no-deps";
  _.plaidml-keras.pipInstallFlags = "--no-deps";
}
```
Let me know if this works for you.

**Comment by tfmoraes** [comment]
Thanks @DavHau! It worked.

**Comment by fluffynukeit** [comment]
Worked for me as well! Thank heavens because I couldn't figure out how to "uninstall enum34" in mach-nix, which is the action that a lot of sites suggest for the enum34 intFlag problem.  This override got my plaidml-keras environment built.
