### ISSUE TITLE
pkg: mariadb

### ISSUE THREAD

**Issue by InLaw** [DavHau/mach-nix#111]
```
let
  mach-nix = import (builtins.fetchGit {
    url = "https://github.com/DavHau/mach-nix/";
    ref = "refs/heads/master";
  });
  py_env = mach-nix.mkPython rec {
    python = mach-nix.nixpkgs.python37;
    requirements =  ''  
    mariadb
      '';
  };
in
(py_env.override ( args:{ignoreCollisions=true; }) ).env
```

leads to 
`The Package 'mariadb' is not available from any of the selected providers {'wheel', 'nixpkgs', 'sdist'}`

**Comment by DavHau** [comment]
Mariadb provides wheel for windows only and the sdist package could not be analyzed my mach-nix' crawler due to:

```
/bin/sh: mariadb_config: not found
Traceback (most recent call last):
  File "<string>", line 5, in <module>
  File "setup.py", line 26, in <module>
    cfg = get_config(options)
  File "/build/mariadb-1.0.1/mariadb_posix.py", line 51, in get_config
    cc_version = mariadb_config(config_prg, "cc_version")
  File "/build/mariadb-1.0.1/mariadb_posix.py", line 28, in mariadb_config
    raise EnvironmentError(
OSError: mariadb_config not found.
Please make sure, that MariaDB Connector/C is installed on your system, edit the configuration file 'site.cfg' and set the 'mariadb_config'
option, which should point to the mariadb_config utility.
```

Their setup.py fails because a external dependency is missing before revealing the python dependencies.

You could fix it upstream or manually build the mariadb packages via `mach-nix.buildPythonPackage`, or just use one of the other mysql connector libs for python, since they should be compatible with mariadb also (I guess?).

**Comment by DavHau** [comment]
A fix for this could be to include the fixes from `./mach_nix/fixes.nix` into the crawler already.

**Comment by DavHau** [comment]
I added some function to mach-nix for fetching pypi sources.
Therefore you can now include mariadb like this:
```nix
let
  mach-nix = import (builtins.fetchGit {
    url = "https://github.com/DavHau/mach-nix/";
    rev = "2ee3786b06ab2c3d7f46c2a7cae3f9c3fa0dc0c9";
  });

in
mach-nix.mkPython {
  extra_pkgs = [
    (mach-nix.buildPythonPackage {
      src = mach-nix.fetchPypiSdist "mariadb" "1.0.2";
      pname = "mariadb";
      version = "1.0.2";
      requirements = "";
      MARIADB_CONFIG = "${mach-nix.nixpkgs.mariadb-connector-c}/bin/mariadb_config";
     })
  ];
}

```

**Comment by InLaw** [comment]
do not work

```
let
  mach-nix = import (builtins.fetchGit {
    url = "https://github.com/DavHau/mach-nix/";
    #ref = "refs/tags/2.4.1";
    #ref = "refs/heads/master";

    rev = "2ee3786b06ab2c3d7f46c2a7cae3f9c3fa0dc0c9";
    #rev = "59d54bd366b10430dc45e46b83dd2c3fb72f29d1" ; # ws
  });

  nixPkgs = import mach-nix.nixpkgs.path {config= { allowUnfree = true; };  };
  #nixPkgs = import mach-nix.nixPkgs.path { };
  py = nixPkgs.python37Packages ;

  py_env = mach-nix.mkPython {
    

    python = nixPkgs.python37;

    extra_pkgs = [
        (mach-nix.buildPythonPackage {
            src = mach-nix.fetchPypiSdist "mariadb" "1.0.2";
            pname = "mariadb";
            version = "1.0.2";
            requirements = "";
            MARIADB_CONFIG = "${nixPkgs.mariadb-connector-c}/bin/mariadb_config";
        })
    ];
    requirements =  ''  
        ipython
        jupyterlab
        pandas 
        seaborn

        mariadb
    
    '';
    

    #_.pyqt5.buildInputs.add = [ nixPkgs.kerberos ];

    providers = {
      numpy = "nixpkgs";
    };


  };
#in (py_env.override ( args:{ignoreCollisions=true; }) ).env
in 
nixPkgs.mkShell rec {
  buildInputs = [
    nixPkgs.bash
    #nixPkgs.mariadb
    #nixPkgs.libmysqlclient
    #nixPkgs.unixODBCDrivers.mariadb
  ]
  ++[
    ( (py_env).override( args:{ignoreCollisions=true; })  )
  ] ;

  shellHook = ''
        # # # 
        ${py_env}/bin/python -c "import mariadb"


        '';
}
```

**Comment by DavHau** [comment]
The problem here is, that mariadb is built using python 3.8, but then included into a python 3.7 based environment.
I should probably catch that case with an error message. Or somehow default to the python version of the outer mkPython call.

In your expression, just add a `python = "python37";` inside `buildPythonPackage` call.

**Comment by InLaw** [comment]
While it works with 2.4.1, py38
it is not working wtih 3.1.1 (e.g. py38)

**Comment by DavHau** [comment]
Maria db is now in nixpkgs and installs fine from that provider
