### ISSUE TITLE
pytorch fails

### ISSUE THREAD

**Issue by DavHau** [DavHau/mach-nix#145]
`nix develop github:davhau/mach-nix#shellWith.pytorch`
fails with:
```
 Traceback (most recent call last):
    File "setup.py", line 732, in <module>
      build_deps()
    File "setup.py", line 308, in build_deps
      check_pydep('yaml', 'pyyaml')
    File "setup.py", line 367, in check_pydep
      raise RuntimeError(missing_pydep.format(importname=importname, module=module))
  RuntimeError: Missing build dependency: Unable to `import yaml`.
  Please install it via `conda install pyyaml` or `pip install pyyaml`
```

**Comment by DavHau** [comment]
Fixed
