### ISSUE TITLE
master: pkg: rpy2

### ISSUE THREAD

**Issue by InLaw** [DavHau/mach-nix#149]
```
let
  mach-nix = import (builtins.fetchGit {
    url = "https://github.com/DavHau/mach-nix.git";
    ref = "refs/heads/master" ;
    rev = "b2aede9aa2f89a7bb150d5927812b3c3e505dcf6"; # new
  } ) { } ; 

  nixPkgs = (import mach-nix.nixpkgs.path {config= { allowUnfree = true;  };} ); # permittedInsecurePackages = [ "openssl-1.0.2u" ];
  py = nixPkgs.python37Packages ;
  R = nixPkgs.rPackages ;

  pkgsNix = import /home/ae/ae_share_VM/z_DS_setup/home-manager/nix/nixPkgs.nix nixPkgs ;

  pkgsR = with R; [
      dplyr
      data_table 
      DataExplorer
  ];

  pyEnv = mach-nix.mkPython rec { 
    pkgs = nixPkgs;
    python = nixPkgs.python37;  
    requirements = '' 
    ipython 
    jupyterlab
    pandas
    seaborn

    rpy2
    '';
    _.rpy2.buildInputs.add = pkgsR ; 

    providers = {
      rpy2                = "nixpkgs" ; 
    };
  };
 envShell = nixPkgs.mkShell rec {   
  buildInputs = 
    [ 
    (pyEnv )
     ]  
  ;

};
in envShell  
```

----

```
error: while evaluating the attribute 'buildInputs' of the derivation 'nix-shell' at /nix/store/n2n1sxx75mfwwnvrm0akifrafympfblh-nixpkgs/pkgs/build-support/mkshell/default.nix:28:3:
'_mkPython' at /nix/store/4i8400z2nj3hffja31r3wg4j0p8gawa0-source/default.nix:253:5 called with unexpected argument 'pkgs', at /nix/store/4i8400z2nj3hffja31r3wg4j0p8gawa0-source/default.nix:250:87
```

**Comment by DavHau** [comment]
I deprecated the `pkgs` argument recently. `pkgs` now have to be passed during import. I also now added a proper deprecation error message. I will release a new version soon and adapt all docs.

This here builds:
(To bring your own nixpkgs, un-comment line 7)
```nix
let
  mach-nix = import (builtins.fetchGit {
    url = "https://github.com/DavHau/mach-nix.git";
    ref = "refs/heads/master" ;
    rev = "aa0d7cb6b3dc4468c3229083eedea01a6f4a7ecd"; # new
  }) { 
    # pkgs = import <nixpkgs> {};
  } ;

  pkgs = mach-nix.nixpkgs;

  pkgsR = with pkgs.rPackages; [
      dplyr
      data_table
      DataExplorer
  ];

  pyEnv = mach-nix.mkPython rec {
    python = "python37";
    requirements = ''
    ipython
    jupyterlab
    pandas
    seaborn

    rpy2
    '';

    _.rpy2.buildInputs.add = pkgsR ;

    providers.rpy2 = "nixpkgs" ;
  };
  envShell = pkgs.mkShell rec {
    buildInputs = [
      pyEnv
    ];
  };
in envShell
```

PS: I'm curious if the R packages actually work. In that case, we should add it to the examples.

**Comment by InLaw** [comment]
```
mport rpy2.robjects as robjects
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nix/store/n068mqbr9kq10sw5cmaj77lpg6kyl7fb-python3-3.7.9-env/lib/python3.7/site-packages/rpy2/robjects/__init__.py", line 19, in <module>
    from rpy2.robjects.robject import RObjectMixin, RObject
  File "/nix/store/n068mqbr9kq10sw5cmaj77lpg6kyl7fb-python3-3.7.9-env/lib/python3.7/site-packages/rpy2/robjects/robject.py", line 10, in <module>
    rpy2.rinterface.initr_simple()
  File "/nix/store/n068mqbr9kq10sw5cmaj77lpg6kyl7fb-python3-3.7.9-env/lib/python3.7/site-packages/rpy2/rinterface.py", line 799, in initr_simple
    status = embedded._initr()
  File "/nix/store/n068mqbr9kq10sw5cmaj77lpg6kyl7fb-python3-3.7.9-env/lib/python3.7/site-packages/rpy2/rinterface_lib/embedded.py", line 119, in _initr
    raise ValueError('openrlib.R_HOME cannot be None.')
ValueError: openrlib.R_HOME cannot be None.

```

**Comment by DavHau** [comment]
I tried with a few different expressions but cannot reproduce the error. Maybe it's due to some recent improvements.
Please also see the example I added here: https://github.com/DavHau/mach-nix/blob/master/examples.md#r-and-python

**Comment by DavHau** [comment]
Closing due to inactivity and me not being able to reproduce. Feel free to add more info in case this problem still exists.
