### ISSUE TITLE
git dependencies in requirements.txt

### ISSUE THREAD

**Issue by GuillaumeDesforges** [DavHau/mach-nix#183]
I have requirements defined with the

```
-e git+https://github.com/user/repo.git#egg=repo
```

syntax which are not loaded:

```
Traceback (most recent call last):
  File "/nix/store/1bmrgs2dy96379nhq645nklpd6asghyl-c87iplsaa2vcw3hhz1p4ykm9iy5ci6dj-source/mach_nix/generate.py", line 94, in <module>
    main()
  File "/nix/store/1bmrgs2dy96379nhq645nklpd6asghyl-c87iplsaa2vcw3hhz1p4ykm9iy5ci6dj-source/mach_nix/generate.py", line 61, in main
    reqs = filter_reqs_by_eval_marker(parse_reqs(requirements), context(py_ver, platform, system))
  File "/nix/store/1bmrgs2dy96379nhq645nklpd6asghyl-c87iplsaa2vcw3hhz1p4ykm9iy5ci6dj-source/mach_nix/cache.py", line 14, in cache_wrapper
    result = tuple(result)
  File "/nix/store/1bmrgs2dy96379nhq645nklpd6asghyl-c87iplsaa2vcw3hhz1p4ykm9iy5ci6dj-source/mach_nix/requirements.py", line 67, in parse_reqs
    reqs = list(pkg_resources.parse_requirements(strs))
  File "/nix/store/in8xcy63iqs38majkx5wbrq19w35f7gn-python3-3.7.9-env/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3103, in parse_requirements
    yield Requirement(line)
  File "/nix/store/in8xcy63iqs38majkx5wbrq19w35f7gn-python3-3.7.9-env/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3112, in __init__
    raise RequirementParseError(str(e))
pkg_resources.RequirementParseError: Invalid requirement, parse error at "'-e git+h'"
```

**Comment by DavHau** [comment]
Those are pip specific CLI arguments written inside a requirements.txt. The parser of mach-nix doesn't support them yet.

I'm open for adding support if somebody wants to provide a PR.

Currently adding arbitrary libs from git can be done inside `packagesExtra` using `fetchGit` or `fetchTarball`.
See example [buildpythonpackage-from-github](https://github.com/DavHau/mach-nix/blob/master/examples.md#buildpythonpackage-from-github)
