### ISSUE TITLE
OSError('sndfile library not found')

### ISSUE THREAD

**Issue by Bietola** [DavHau/mach-nix#189]
Here is my shell.nix:

``` nix
{ pkgs ? import <nixpkgs> {} }:

let
  mach-nix = import (
    builtins.fetchGit {
      url = "https://github.com/DavHau/mach-nix/";
      ref = "refs/tags/3.1.1";
    }
  ) {
    python = "python37";
  };

  customPython = mach-nix.mkPython {
    requirements = ''
      tensorflow
      umap-learn
      visdom
      librosa>=0.8.0
      matplotlib>=3.3.0
      numpy==1.19.3; platform_system == "Windows"
      numpy==1.19.4; platform_system != "Windows"
      scipy>=1.0.0
      tqdm
      sounddevice
      SoundFile
      Unidecode
      inflect
      PyQt5
      multiprocess
      numba
    '';
  };
in

pkgs.mkShell {
  buildInputs = [
    customPython
  ];
}
```

When running `nix-shell` it doesn't work... giving me the following error:

```
builder for '/nix/store/vkm7kl5zc1k836r2wlqb0h8fjyrbchs5-python3.7-librosa-0.8.0.drv' failed with exit code 1
cannot build derivation '/nix/store/4f3673z0pih2dxpiyjq08rzp141sq83h-python3-3.7.9-env.drv': 1 dependencies couldn't be built
error: build of '/nix/store/4f3673z0pih2dxpiyjq08rzp141sq83h-python3-3.7.9-env.drv' failed
```

I also get some other error looking thing before the failed derivation (which I am guessing is the problem) which references a missing soundfile library:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <lambda>
  File "/nix/store/w5rhnscn5jxxy4ichr6f3gmv0mpa4x8g-python3-3.7.9/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/nix/store/6gwnbkrwy1gz2qlgvp9ykrcn8cz20dag-python3.7-librosa-0.8.0/lib/python3.7/site-packages/librosa/__init__.py", line 211, in <module>
    from . import core
  File "/nix/store/6gwnbkrwy1gz2qlgvp9ykrcn8cz20dag-python3.7-librosa-0.8.0/lib/python3.7/site-packages/librosa/core/__init__.py", line 6, in <module>
    from .audio import *  # pylint: disable=wildcard-import
  File "/nix/store/6gwnbkrwy1gz2qlgvp9ykrcn8cz20dag-python3.7-librosa-0.8.0/lib/python3.7/site-packages/librosa/core/audio.py", line 8, in <module>
    import soundfile as sf
  File "/nix/store/wy5xshpg0j6ba3p9ybp12g7yr5bi0jbj-python3.7-soundfile-0.10.3.post1/lib/python3.7/site-packages/soundfile.py", line 142, in <module>
    raise OSError('sndfile library not found')
OSError: sndfile library not found
```

I tried mentioning the pkgs.libsndfile library in the non-python dependecies below

```
...
pkgs.mkShell {
  buildInputs = [
    pkgs.libsndfile
    customPython
  ];
```

But nothing changed. Where should I specify this non-python dependency? Is this even my real problem here?

**Comment by DavHau** [comment]
You can see in the traceback that librosa failed because of the missing dep. Therefore you'd have to add it as a buildInput to librosa directly. The easiest way to do that would be using [simplified overrides](https://github.com/DavHau/mach-nix/blob/master/examples.md#simplified-overrides-_-argument).

Alternatively your problem is also fixed by taking soundfile from nixpkgs:
Just put `providers.soundfile = "nixpkgs";` inside mkPython

**Comment by Bietola** [comment]
The solution worked! Thanks a lot.
