### ISSUE TITLE
ImportError: Failed to import any qt binding

### ISSUE THREAD

**Issue by Bietola** [DavHau/mach-nix#193]
I am trying to run a python script from a project that has the following install instructions:

- install pytorch.
- install ffmpeg.
- Run pip install -r requirements.txt to install the remaining necessary packages.

Here is *requirements.txt*:

```
tensorflow==1.15
umap-learn
visdom
librosa>=0.8.0
matplotlib>=3.3.0
numpy==1.19.3; platform_system == "Windows"
numpy==1.19.4; platform_system != "Windows"
scipy>=1.0.0
tqdm
sounddevice
SoundFileich,
Unidecode
inflect
PyQt5
multiprocess
numba
```

As I am using nixos, I tried to create a shell.nix file that would be suitable to use this project. Here is my attempt so far:

``` nix
{ pkgs ? import <nixpkgs> {} }:

let
  mach-nix = import (
    builtins.fetchGit {
      url = "https://github.com/DavHau/mach-nix/";
      ref = "refs/tags/3.1.1";
    }
  ) {
    python = "python37";
  };

  customPython = mach-nix.mkPython {
    providers.soundfile = "nixpkgs";

    requirements = ''
      tensorflow
      umap-learn
      visdom
      librosa>=0.8.0
      matplotlib>=3.3.0
      numpy==1.19.3; platform_system == "Windows"
      numpy==1.19.4; platform_system != "Windows"
      scipy>=1.0.0
      tqdm
      sounddevice
      SoundFile
      Unidecode
      inflect
      PyQt5
      multiprocess
      numba
    '';
  };
in

pkgs.mkShell {
  buildInputs = [
    pkgs.ffmpeg
    pkgs.python37Packages.pytorch
    customPython
  ];
}
```

Running `nix-shell` works, but as soon as I run the scipt which is needed to access the project's gui (with the command `python demo_toolbox.py` I get the following error:

```
[...]
raise ImportError("Failed to import any qt binding")
ImportError: Failed to import any qt binding
```

Which confuses me... since I have specified PyQt5 as a dependency in my `shell.nix` file.

In case someone wishes to reproduce this, the project is here: https://github.com/CorentinJ/Real-Time-Voice-Cloning. Just follow the instructions using the `shell.nix` I specified above.

Thanks in advance for your time.

**Comment by DavHau** [comment]
The pyqt5 wheel distribution from pypi is quite broken since it has lots of unsatisfied dependencies.
I'd recommend taking pyqt5 from nixpkgs. Sadly this will trigger a rebuild of pyqt.
To avoid the build time, you could alternatively try the `conda-beta` branch of mach-nix and get pyqt from conda. (On conda it's named pyqt, without 5).
Also sounddevice seems to have a missing dependency when installed from pypi. Therefore better get it from nixpkgs.

**Comment by InLaw** [comment]
` rev = "65266b5cc867fec2cb6a25409dd7cd12251f6107";`

```
providers = {        
        pyqt5 =   "nixpkgs" ; 
}
```
`
_.pyqt5.add     = (with nixPkgs; [   xvfb-run ] ) ++ (with py ; [ pyqt5_sip pyqt-builder  pyqt5_with_qtwebkit  pyqtwebengine]);`

I cannot see that this would work:


```
Processing /build/PyQt5-5.15.4
  Running command Preparing metadata (pyproject.toml)
  Traceback (most recent call last):
    File "/nix/store/88rav859ms3skzrkyx273sd39k6mvmr9-python3.9-pip-22.1.2/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 156, in prepare_metadata_for_build_wheel
      hook = backend.prepare_metadata_for_build_wheel
  AttributeError: module 'sipbuild.api' has no attribute 'prepare_metadata_for_build_wheel'

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/nix/store/wagpy0rsch98hppmha9gpdkpyb0ggszc-python3.9-sip-6.2.0/lib/python3.9/site-packages/sipbuild/abstract_project.py", line 121, in import_callable
      spec.loader.exec_module(module)
    File "<frozen importlib._bootstrap_external>", line 850, in exec_module
    File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
    File "project.py", line 25, in <module>
      from pyqtbuild import PyQtBindings, PyQtProject, QmakeTargetInstallable
  ModuleNotFoundError: No module named 'pyqtbuild'

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/nix/store/88rav859ms3skzrkyx273sd39k6mvmr9-python3.9-pip-22.1.2/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
      main()
    File "/nix/store/88rav859ms3skzrkyx273sd39k6mvmr9-python3.9-pip-22.1.2/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/nix/store/88rav859ms3skzrkyx273sd39k6mvmr9-python3.9-pip-22.1.2/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 160, in prepare_metadata_for_build_wheel
      whl_basename = backend.build_wheel(metadata_directory, config_settings)
    File "/nix/store/wagpy0rsch98hppmha9gpdkpyb0ggszc-python3.9-sip-6.2.0/lib/python3.9/site-packages/sipbuild/api.py", line 51, in build_wheel
      project = AbstractProject.bootstrap('pep517')
    File "/nix/store/wagpy0rsch98hppmha9gpdkpyb0ggszc-python3.9-sip-6.2.0/lib/python3.9/site-packages/sipbuild/abstract_project.py", line 68, in bootstrap
      project_factory = cls.import_callable(default_factory_py, cls)
    File "/nix/store/wagpy0rsch98hppmha9gpdkpyb0ggszc-python3.9-sip-6.2.0/lib/python3.9/site-packages/sipbuild/abstract_project.py", line 123, in import_callable
      raise UserException("Unable to import '{0}'".format(name),
  sipbuild.exceptions.UserException
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /nix/store/m0yjnrbw2055ckkm729xggl2lxnzzhs9-python3-3.9.13/bin/python3.9 /nix/store/88rav859ms3skzrkyx273sd39k6mvmr9-python3.9-pip-22.1.2/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /build/tmpw_rk69z5
  cwd: /build/PyQt5-5.15.4
  Preparing metadata (pyproject.toml) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
error: builder for '/nix/store/cgqznck22yidra5gd6kq74582js8knbs-python3.9-pyqt5-5.15.4.drv' failed with exit code 1;
       last 10 log lines:
       >   full command: /nix/store/m0yjnrbw2055ckkm729xggl2lxnzzhs9-python3-3.9.13/bin/python3.9 /nix/store/88rav859ms3skzrkyx273sd39k6mvmr9-python3.9-pip-22.1.2/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /build/tmpw_rk69z5
       >   cwd: /build/PyQt5-5.15.4
       >   Preparing metadata (pyproject.toml) ... error
       > error: metadata-generation-failed
       >
       > × Encountered error while generating package metadata.
       > ╰─> See above for output.
       >
       > note: This is an issue with the package mentioned above, not pip.
       > hint: See above for details.
       For full logs, run 'nix log /nix/store/cgqznck22yidra5gd6kq74582js8knbs-python3.9-pyqt5-5.15.4.drv'.
error: 1 dependencies of derivation '/nix/store/fjjff5xxdih8qcjcqpxjfx8kpl4cfmm0-python3-3.9.13-env.drv' failed to build
error: 1 dependencies of derivation '/nix/store/d6czppfxxkm0qrn3hi9y9mbmw172w1jj-buildEnv__tmpl.drv' failed to build
```
