### ISSUE TITLE
python - selenium - selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH

### ISSUE THREAD

**Issue by InLaw** [DavHau/mach-nix#203]
How to work with selenium via mach-nix?

```
let
  pyVersion = "37"; 
  mach-nix = import (builtins.fetchGit {
    url = "https://github.com/DavHau/mach-nix/";
    ref = "refs/tags/3.1.1" ; 
    #ref = "refs/heads/conda-beta";
  }) { 
      python = "python${pyVersion}"; 
    };  

  nixPkgs = import mach-nix.nixpkgs.path {config= { allowUnfree = true;  }; };
  py = nixPkgs."python${pyVersion}Packages" ;

in let
  envPy = mach-nix.mkPython rec {
    requirements =  ''
        ipython 
        jupyterlab
        #pandas

        selenium
        pytest-webdriver

        browsermob-proxy 

        webdriver_manager

        geckodriver-autoinstaller
      ''; 

      packagesExtra = []
          ++ [
            nixPkgs.chromedriver
          ]
      ; 

      providers = {
      };
  };
in (envPy).env

# from selenium import webdriver;  browser = webdriver.Chrome();
```

`
from selenium import webdriver;  driver = webdriver.Chrome()`

```
Traceback (most recent call last):
  File "/nix/store/7kbw8xsw7hsj9zdgcgwvp8lymxxl5g70-python3-3.8.6-env/lib/python3.8/site-packages/selenium/webdriver/common/service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "/nix/store/5aq2ix4vmk8bxs20ddqi48vc4bnk8zr5-python3-3.8.6/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/nix/store/5aq2ix4vmk8bxs20ddqi48vc4bnk8zr5-python3-3.8.6/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'chromedriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/nix/store/7kbw8xsw7hsj9zdgcgwvp8lymxxl5g70-python3-3.8.6-env/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/nix/store/7kbw8xsw7hsj9zdgcgwvp8lymxxl5g70-python3-3.8.6-env/lib/python3.8/site-packages/selenium/webdriver/common/service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home
```

----
conda-beta:

```
warning: unknown setting 'experimental-features'
trace: using conda channels: main, r
these derivations will be built:
  /nix/store/akwyy01ayhlaqfnpa5bd8xbv3ri18x7j-python3.8-jupyterlab-2.2.6.drv
  /nix/store/vb1k7c6ldrflf4dcgdg6nhhl4mqv0cvv-python3.8-selenium-3.141.0.drv
  /nix/store/d73cng19cl9fj9mb562alfc1gn9p37lf-python3-3.8.6-env.drv
  /nix/store/cn20gnl9myxnakdxx0sfw3wfzdcajc0b-python3-3.8.6-env.drv
  /nix/store/pfphdswq53g9bw8vn186yp4n0jsdg9bs-bEnvJL.drv
warning: unknown setting 'experimental-features'
building '/nix/store/akwyy01ayhlaqfnpa5bd8xbv3ri18x7j-python3.8-jupyterlab-2.2.6.drv'...
building '/nix/store/vb1k7c6ldrflf4dcgdg6nhhl4mqv0cvv-python3.8-selenium-3.141.0.drv'...
Sourcing python-recompile-bytecode-hook.sh
Sourcing python-remove-tests-dir-hook
Sourcing python-catch-conflicts-hook.sh
Sourcing python-remove-bin-bytecode-hook.sh
Sourcing python-imports-check-hook.sh
Using pythonImportsCheckPhase
Sourcing python-namespaces-hook
unpacking sources
Sourcing python-recompile-bytecode-hook.sh
Sourcing python-remove-tests-dir-hook
Sourcing python-catch-conflicts-hook.sh
Sourcing python-remove-bin-bytecode-hook.sh
Sourcing python-imports-check-hook.sh
Using pythonImportsCheckPhase
Sourcing python-namespaces-hook
patching sources
configuring
no configure script, doing nothing
building
no Makefile, doing nothing
installing
post-installation fixup
shrinking RPATHs of ELF executables and libraries in /nix/store/l1dgr6h0niagc591b59j2q50fxmpxl7w-python3.8-selenium-3.141.0
shrinking /nix/store/l1dgr6h0niagc591b59j2q50fxmpxl7w-python3.8-selenium-3.141.0/lib/python3.8/site-packages/selenium/webdriver/firefox/amd64/x_ignore_nofocus.so
shrinking /nix/store/l1dgr6h0niagc591b59j2q50fxmpxl7w-python3.8-selenium-3.141.0/lib/python3.8/site-packages/selenium/webdriver/firefox/x86/x_ignore_nofocus.so
strip is /nix/store/p3kn26g5nhmx6spn37ar3mn0xjbzks3g-binutils-2.31.1/bin/strip
stripping (with command strip and flags -S) in /nix/store/l1dgr6h0niagc591b59j2q50fxmpxl7w-python3.8-selenium-3.141.0/lib
patching script interpreter paths in /nix/store/l1dgr6h0niagc591b59j2q50fxmpxl7w-python3.8-selenium-3.141.0
checking for references to /build/ in /nix/store/l1dgr6h0niagc591b59j2q50fxmpxl7w-python3.8-selenium-3.141.0...
unpacking sources
Executing pythonRemoveTestsDir
Finished executing pythonRemoveTestsDir
automatically fixing dependencies for ELF files
searching for dependencies of /nix/store/l1dgr6h0niagc591b59j2q50fxmpxl7w-python3.8-selenium-3.141.0/lib/python3.8/site-packages/selenium/webdriver/firefox/amd64/x_ignore_nofocus.so
searching for dependencies of /nix/store/l1dgr6h0niagc591b59j2q50fxmpxl7w-python3.8-selenium-3.141.0/lib/python3.8/site-packages/selenium/webdriver/firefox/x86/x_ignore_nofocus.so
patching sources
configuring
builder for '/nix/store/vb1k7c6ldrflf4dcgdg6nhhl4mqv0cvv-python3.8-selenium-3.141.0.drv' failed with exit code 1
cannot build derivation '/nix/store/cn20gnl9myxnakdxx0sfw3wfzdcajc0b-python3-3.8.6-env.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/pfphdswq53g9bw8vn186yp4n0jsdg9bs-bEnvJL.drv': 1 dependencies couldn't be built
error: build of '/nix/store/pfphdswq53g9bw8vn186yp4n0jsdg9bs-bEnvJL.drv' failed

```

**Comment by DavHau** [comment]
You could do a:
```
packagesExtra = [ pkgs.chromedriver ];
```
It requires the chromedriver version 85, so you might want to check which chromedriver version is used in your nixpkgs branch.
The current nixos-20.09 branch should have version 85.

**Comment by InLaw** [comment]
chrome 85 is used
added chromedriver in packagesExtra and in the mkShell aswell 
- without success / error is the same

**Comment by InLaw** [comment]
sorry for the nixFlakes script, now I updated it to the real script used.

**Comment by InLaw** [comment]
got a solution:

```
let
  pyVersion = "37"; 
  mach-nix = import (builtins.fetchGit {
    url = "https://github.com/DavHau/mach-nix/";
    ref = "refs/tags/3.1.1" ; 
    #ref = "refs/heads/conda-beta";
  }) { 
      pkgs= import <nixpkgs>  {config= { allowUnfree = true; }; };
      python = "python${pyVersion}"; 
    };  

  nixPkgs = import mach-nix.nixpkgs.path {}; # import mach-nix.nixpkgs.path {config= { allowUnfree = true;  }; };
  py = nixPkgs."python${pyVersion}Packages" ;

in let
  envPy = mach-nix.mkPython rec {
    requirements =  ''
        ipython 
        jupyterlab
        #pandas

        selenium
        pytest-webdriver

        browsermob-proxy 

        webdriver_manager

        geckodriver-autoinstaller
      ''; 

      packagesExtra = []
          ++ [
            nixPkgs.chromedriver
          ]
      ; 

      providers = {
      };
  };
in (envPy).env
```
