### ISSUE TITLE
Resolver too Deep  for Datashader and Intake Combo

### ISSUE THREAD

**Issue by rowhit** [DavHau/mach-nix#212]
I am trying to build the following nix shell environment. 
```nix :tangle shell.nix
{ 
  sources ?  import ./nix/sources.nix
, pkgs ?  import sources.nixpkgs {}
}:

let
  mach-nix = import (builtins.fetchGit {
    url = "https://github.com/DavHau/mach-nix/";
    ref = "refs/tags/3.1.1";
  }) 
  { 
      pkgs= import <nixpkgs>  {config= { allowUnfree = true; }; };
      python = "python38"; 
  };

  pythonPkgsWithMach = mach-nix.mkPython rec {
    requirements =  '' 

      napari==0.2.0
      vispy==0.6.5

      # rapids

      tensorflow==2.3.1
      cartopy==0.18.0
      # intake[complete]
      intake==0.6.0
      # intake-parquet
      # intake-xarray
      s3fs==0.5.1
      jupyterlab==2.2.9
      ipython==7.19.0
      numpy==1.18.5
      pandas==1.1.4

      xarray==0.16.1
      arrow==0.17.0
      pyarrow==2.0.0
      zarr==2.5.0
      ipympl==0.5.8
      ipywidgets==7.5.1

      seaborn==0.11.0

      geoviews==1.8.1
      geopandas==0.8.1

      modin[dask]
      # modin[dask]==0.8.2
      # dask[complete]==2.19.0
      # dask[array]
      # dask[bag]
      # dask[dataframe]
      # dask[delayed]

      # datashader : conflicts with intaker
      datashader
      matplotlib==3.3.3
      bokeh==2.2.3
      panel==0.10.2
      param==1.10.0
      colorcet==2.0.2
      pygraphviz==1.6

      # holoviz : metapackage for hvplot etc
      altair==4.1.0
      # holoviews : corrupts intake and dask combo is provided thought by hvplot
      holoviews==1.13.5
      hvplot==0.7.0

      # vega
      vega_datasets==0.8.0

      sympy==1.6.2

      scipy==1.5.4
      torch==1.7.0
      keras-applications==1.0.8
      keras-preprocessing==1.1.2

      streamz==0.6.1

      fastparquet==0.4.1
      fiona==1.8.18

      pyqt5==5.15.2
      pyside2==5.15.2

      selenium==3.141.0
    '';

    providers = {
        fastparquet="nixpkgs,wheel";
        pytest-runner = "nixpkgs";
        fiona = "nixpkgs";
        colorcet = "nixpkgs";
    };
  };

in

pkgs.mkShell rec {
  name = "72547b06-machnix-datascience-light";
  buildInputs = [ 
    pythonPkgsWithMach

    pkgs.which
    pkgs.openssl
    pkgs.qt5.full

    pkgs.gcc
    pkgs.nodejs
    pkgs.parquet-cpp

    pkgs.geos
    pkgs.snappy
    pkgs.graphviz
    pkgs.pkgconf
    pkgs.geckodriver
    pkgs.firefox

    pkgs.python38Packages.python-snappy

  ];

  shellHook = ''
    export ENVNAME="${name}"
  '';
}
```
But I receive the resolver too deep. This conflict is primarily due to datashader and intake. I can install one or the other without issue but when I try to enable both I get the error shown below:
```sh
building '/nix/store/yf80l3axfd384mp7xdwrdxqkqzwyvyny-mach_nix_file.drv'...
Traceback (most recent call last):
  File "/nix/store/1bmrgs2dy96379nhq645nklpd6asghyl-c87iplsaa2vcw3hhz1p4ykm9iy5ci6dj-source/mach_nix/generate.py", line 94, in <module>
    main()
  File "/nix/store/1bmrgs2dy96379nhq645nklpd6asghyl-c87iplsaa2vcw3hhz1p4ykm9iy5ci6dj-source/mach_nix/generate.py", line 63, in main
    expr = generator.generate(reqs)
  File "/nix/store/1bmrgs2dy96379nhq645nklpd6asghyl-c87iplsaa2vcw3hhz1p4ykm9iy5ci6dj-source/mach_nix/generators/overides_generator.py", line 35, in generate
    pkgs = self.resolver.resolve(reqs)
  File "/nix/store/1bmrgs2dy96379nhq645nklpd6asghyl-c87iplsaa2vcw3hhz1p4ykm9iy5ci6dj-source/mach_nix/resolver/resolvelib_resolver.py", line 63, in resolve
    result = resolvelib.Resolver(Provider(self.nixpkgs, self.deps_provider), reporter).resolve(reqs, max_rounds=1000)
  File "/nix/store/73i2pdw77apbz2z2r79pi34ksjjj8v8y-python3-3.7.9-env/lib/python3.7/site-packages/resolvelib/resolvers.py", line 413, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/nix/store/73i2pdw77apbz2z2r79pi34ksjjj8v8y-python3-3.7.9-env/lib/python3.7/site-packages/resolvelib/resolvers.py", line 323, in resolve
    raise ResolutionTooDeep(max_rounds)
resolvelib.resolvers.ResolutionTooDeep: 1000
builder for '/nix/store/yf80l3axfd384mp7xdwrdxqkqzwyvyny-mach_nix_file.drv' failed with exit code 1
error: build of '/nix/store/yf80l3axfd384mp7xdwrdxqkqzwyvyny-mach_nix_file.drv' failed
(use '--show-trace' to show detailed location information)
```

I am clueless as to how to fix this. The  "--show-trace" option does not spit any valuable information either.

Regards,
Rohit

**Comment by rowhit** [comment]
Removing the version constraints for packages solves the issue.
