### ISSUE TITLE
Unable to use tkinter package

### ISSUE THREAD

**Issue by iilyak** [DavHau/mach-nix#228]
I tried to use mach-nix in combination with flakes. IT fails with the following error which I am unable to resolve:
```
nix-shell
warning: Git tree '/home/iilyak/dev/test' is dirty
error: --- ThrownError -------------------------------------------------------------------------------------------------------------------------------------------- nix-shell
Automatic extraction of 'pname' from python package source /nix/store/f7018yxi4ash7wq1ns84h9kkqyv9mz4b-python3.8-tkinter-3.8.7 failed.
Please manually specify 'pname'
(use '--show-trace' to show detailed location information)
```

It works fine without flakes. I am very new to nix and obviously doing something wrong.

# `flakes.nix`

```
{
  description = "Testing flakes for python";

  inputs = {
    flake-compat = {
      url = "github:edolstra/flake-compat";
      flake = false;
    };

    mach-nix = {
        url = "github:davhau/mach-nix/master";
        inputs.nixpkgs.follows = "nixpkgs";
    };

    nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";

    utils.url = "github:numtide/flake-utils";
  };
  outputs = { self, flake-compat, nixpkgs, utils, mach-nix }:
    utils.lib.eachDefaultSystem (system:
      let
        pkgs = (import nixpkgs { inherit system; }).pkgs;
        mach-nix-utils = import mach-nix {
          inherit pkgs;
          python = "python3";
        };

        pythonPackages = pkgs.python38Packages;

      in {

        devShell = mach-nix-utils.mkPythonShell {
          requirements = builtins.readFile ./requirements.txt;
          packagesExtra = [
            pythonPackages.tkinter
          ];
        };
      }
    );
}
```

# `requirements.txt`
empty file

# shell.nix

```
(import (let lock = builtins.fromJSON (builtins.readFile ./flake.lock);
in fetchTarball {
  url =
    "https://github.com/edolstra/flake-compat/archive/${lock.nodes.flake-compat.locked.rev}.tar.gz";
  sha256 = lock.nodes.flake-compat.locked.narHash;
}) { src = ./.; }).shellNix
```

**Comment by DavHau** [comment]
Python packages from nixpkgs should not be used in packagesExtra. I should catch that with a better error message. Instead just have tkinter in your requirements.txt.
If you want tkinter to be taken from nixpkgs, you can specify this via provider settings.

**Comment by InLaw** [comment]
in nixpkgs tkinter is included only ine.g.  `pkgs.python38Full` not in slim python like versions like `pkgs.python3`
- because it's a build in module of Python 3.x it does not exist in Pypi anymore 
--  provider should be default to nixpkgs (in conda it's called ["tk" ](https://anaconda.org/conda-forge/tk) only)

**Comment by InLaw** [comment]
if you add tkinter to the requirements, it results in:

```
let mach-nix = import (builtins.fetchGit {
  url = "https://github.com/DavHau/mach-nix";
  ref = "refs/heads/conda-beta";
  rev= "c407c2e98cbfc847bd4c9c150a2337c9940bd2e5";
    }) {
      python = "python38";
    }; 
in
mach-nix.mkPython {
  requirements = ''
    tkinter
  '';
  providers = {
    tkinter = "nixpkgs";
  };
}
```

```
The Package 'tkinter' (build: None) is not available from any of the selected providers ['nixpkgs']
 for the selected python version

Some requirements could not be resolved.
Top level requirements:
  tkinter  
Providers:
  {'_default': ['conda/main', 'conda/r', 'wheel', 'sdist', 'nixpkgs'],
   'gdal': ['nixpkgs'],
   'pip': ['nixpkgs', 'sdist'],
   'pypy': ['conda/conda-forge'],
   'python-abi': ['conda/conda-forge'],
   'qcfractal': ['conda/conda-forge'],
   'qcfractal-core': ['conda/conda-forge'],
   'setupmeta': ['wheel'],
   'setuptools': ['nixpkgs'],
   'tk': ['conda/conda-forge'],
   'tkinter': ['nixpkgs'],
   'wheel': ['nixpkgs', 'sdist']}
Mach-nix version: conda-beta
Python: 3.8.6
Cause: Requirements conflict: tkinter
The requirements which caused the error:
  tkinter
```

**Comment by iilyak** [comment]
If package is not available is it possible to build it and use it in requirements? Note in this case it would depend on some C libraries.

**Comment by InLaw** [comment]
- it is included in python3xFull
- you could use [mach-nix conda-beta] and use tk in requirements

- it a [module](https://github.com/python/cpython/tree/master/Lib/tkinter/) in cpython / as [package](http://www.tcl.tk/software/tcltk/download.html) 
- you could build it from [conda-forge](https://anaconda.org/conda-forge/tk) pkgs 

it does not look funny to [build](https://github.com/NixOS/nixpkgs/blob/nixos-20.09/pkgs/development/interpreters/python/cpython/default.nix) it youself

**Comment by iilyak** [comment]
> you could use [mach-nix conda-beta] and use tk in requirements

I was able to build environment and switch into it with `> nix-shell`. However the tkinter is acting out.

```
> python3.8
Python 3.8.6 (default, Sep 23 2020, 13:54:27)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tkinter
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nix/store/5aq2ix4vmk8bxs20ddqi48vc4bnk8zr5-python3-3.8.6/lib/python3.8/tkinter/__init__.py", line 36, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ModuleNotFoundError: No module named '_tkinter'
```

**Comment by iilyak** [comment]
Setting the `python38Full` and `providers.tk = "nixpkgs"` helped:

```
{
  description = "Testing flakes for python";

  inputs = {
    flake-compat = {
      url = "github:edolstra/flake-compat";
      flake = false;
    };

    mach-nix = {
       url = "github:davhau/mach-nix/conda-beta";
    };

    nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";

    utils.url = "github:numtide/flake-utils";
  };
  outputs = { self, flake-compat, nixpkgs, utils, mach-nix }:
    utils.lib.eachDefaultSystem (system:
      let
        pkgs = (import nixpkgs { inherit system; }).pkgs;
        mach-nix-utils = import mach-nix {
          python = "python38Full";
        };

      in {
        devShell = mach-nix-utils.mkPythonShell {
          requirements = builtins.readFile ./requirements.txt;
          providers.tk = "nixpkgs";
        };
      }
    );
}

```


Thank you very much for pointers.
