### ISSUE TITLE
cross-platform (abi-related?) inconsistency on older python versions (<3.8?)

### ISSUE THREAD

**Issue by abathur** [DavHau/mach-nix#242]
I've been banging my head against some odd behavior. I'm not sure if you'll have a fix, but hopefully documenting it will save someone else the same pain.

<details>
<summary>A boiled-down version of the setup:</summary>

```nix
# inputs.nix
with builtins;
let
  lock = fromTOML (readFile ./lock.toml);
in rec {
  pkgs = import (builtins.fetchTarball {
    name = "nixpkgs";
    url = "https://github.com/nixos/nixpkgs/tarball/${lock.nixpkgs.rev}";
    sha256 = "${lock.nixpkgs.sha256}";
  }) { config = {}; overlays = []; };
  mach-nix = import (builtins.fetchTarball {
    url = "https://github.com/DavHau/mach-nix/tarball/${lock.mach-nix.rev}";
    sha256 = lock.mach-nix.sha256;
  }) {
    python = "python36";
    inherit pkgs;
  };
}
```

```nix
# python.nix
let
  inputs = (import ./inputs.nix);
in with inputs;
(mach-nix.mkPython {
  requirements = builtins.readFile combined_reqs;
  overridesPre = [(pySelf: pySuper: {
    private_module = mach-nix.buildPythonPackage ...;
  })];
})
```
</details>

The important bits: we're using python36 and have a private package which is listed in the requirements and added in overridesPre.

This builds fine on my local macOS system, but it's failing to find the private package in CI (gitlab-ci, docker nixos/nix image):
```
The Package 'private_module' is not available from any of the selected providers {'nixpkgs', 'sdist', 'wheel'} for the selected python version
```

I banged my head on this for a good bit before realizing there were `python.log` files in the store, with the following stack:
```
Failed to import the site module
Traceback (most recent call last):
  File "/nix/store/gf9vmzyqwyxgf77bsxgsz3zckyhv1pmb-python3-3.6.12-env-patched/lib/python3.6/site.py", line 553, in <module>
    main()
  File "/nix/store/gf9vmzyqwyxgf77bsxgsz3zckyhv1pmb-python3-3.6.12-env-patched/lib/python3.6/site.py", line 539, in main
    known_paths = addusersitepackages(known_paths)
  File "/nix/store/gf9vmzyqwyxgf77bsxgsz3zckyhv1pmb-python3-3.6.12-env-patched/lib/python3.6/site.py", line 282, in addusersitepackages
    user_site = getusersitepackages()
  File "/nix/store/gf9vmzyqwyxgf77bsxgsz3zckyhv1pmb-python3-3.6.12-env-patched/lib/python3.6/site.py", line 258, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/nix/store/gf9vmzyqwyxgf77bsxgsz3zckyhv1pmb-python3-3.6.12-env-patched/lib/python3.6/site.py", line 248, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/nix/store/gf9vmzyqwyxgf77bsxgsz3zckyhv1pmb-python3-3.6.12-env-patched/lib/python3.6/sysconfig.py", line 601, in get_config_var
    return get_config_vars().get(name)
  File "/nix/store/gf9vmzyqwyxgf77bsxgsz3zckyhv1pmb-python3-3.6.12-env-patched/lib/python3.6/sysconfig.py", line 550, in get_config_vars
    _init_posix(_CONFIG_VARS)
  File "/nix/store/gf9vmzyqwyxgf77bsxgsz3zckyhv1pmb-python3-3.6.12-env-patched/lib/python3.6/sysconfig.py", line 421, in _init_posix
    _temp = __import__(name, globals(), locals(), ['build_time_vars'], 0)
ModuleNotFoundError: No module named '_sysconfigdata__linux_x86_64-linux-gnu'
```

I opened a `nix-shell -p python3` and successfully imported it there:
```
>>> __import__("_sysconfigdata__linux_x86_64-linux-gnu")
<module '_sysconfigdata__linux_x86_64-linux-gnu' from '/nix/store/m7080pw0ryjk0jhljp55rq1hd2qy8gki-python3-3.8.6/lib/python3.8/_sysconfigdata__linux_x86_64-linux-gnu.py'>
```

I didn't know what to make of this, but eventually I had the sense to run find over the store for all of these `_sysconfigdata*.py` files:

```console
runner--project-0-concurrent-0:/builds/project-0# find /nix/store -name "_sysconfigdata*.py"
/nix/store/14h1xiy98sd7ks1pbf94zv93pj5d1axa-python3-3.8.7-env/lib/python3.8/site-packages/_sysconfigdata__linux_x86_64-linux-gnu.py
/nix/store/14h1xiy98sd7ks1pbf94zv93pj5d1axa-python3-3.8.7-env/lib/python3.8/_sysconfigdata__linux_x86_64-linux-gnu.py
/nix/store/fg7bbgshp0zadayr28yhsmrrivl500vi-python3-3.7.9/lib/python3.7/site-packages/_sysconfigdata_m_linux_x86_64-linux-gnu.py
/nix/store/fg7bbgshp0zadayr28yhsmrrivl500vi-python3-3.7.9/lib/python3.7/_sysconfigdata_m_linux_x86_64-linux-gnu.py
/nix/store/32w2wdjs566b8q6vwlwcg8h35rrw9dwi-python3-3.6.12-env/lib/python3.6/site-packages/_sysconfigdata_m_linux_x86_64-linux-gnu.py
/nix/store/32w2wdjs566b8q6vwlwcg8h35rrw9dwi-python3-3.6.12-env/lib/python3.6/_sysconfigdata_m_linux_x86_64-linux-gnu.py
/nix/store/a3fjl4gk7mcm4nwpdil7mkikg2irgqln-python-2.7.18/lib/python2.7/_sysconfigdata.py
/nix/store/5fdilxc5dpzvrqxxsq10fl6304xs4c5s-python3-3.7.9-env/lib/python3.7/site-packages/_sysconfigdata_m_linux_x86_64-linux-gnu.py
/nix/store/5fdilxc5dpzvrqxxsq10fl6304xs4c5s-python3-3.7.9-env/lib/python3.7/_sysconfigdata_m_linux_x86_64-linux-gnu.py
/nix/store/yws041px65cq9l9s03jv3hv18wwkfmaz-python-2.7.18/lib/python2.7/_sysconfigdata.py
/nix/store/m7080pw0ryjk0jhljp55rq1hd2qy8gki-python3-3.8.6/lib/python3.8/_sysconfigdata__linux_x86_64-linux-gnu.py
/nix/store/wkw6fsjasr7jbbrlakxxpbiapa8hws42-python3-3.8.7/lib/python3.8/site-packages/_sysconfigdata__linux_x86_64-linux-gnu.py
/nix/store/wkw6fsjasr7jbbrlakxxpbiapa8hws42-python3-3.8.7/lib/python3.8/_sysconfigdata__linux_x86_64-linux-gnu.py
/nix/store/lw9ibyvhxig6q3w2c2fpwvhs2nw6d24w-python3-3.6.12/lib/python3.6/site-packages/_sysconfigdata_m_linux_x86_64-linux-gnu.py
/nix/store/lw9ibyvhxig6q3w2c2fpwvhs2nw6d24w-python3-3.6.12/lib/python3.6/_sysconfigdata_m_linux_x86_64-linux-gnu.py
/nix/store/gf9vmzyqwyxgf77bsxgsz3zckyhv1pmb-python3-3.6.12-env-patched/lib/python3.6/site-packages/_sysconfigdata_m_linux_x86_64-linux-gnu.py
/nix/store/gf9vmzyqwyxgf77bsxgsz3zckyhv1pmb-python3-3.6.12-env-patched/lib/python3.6/_sysconfigdata_m_linux_x86_64-linux-gnu.py
```

The last of these happens to be the same python install that produced the error:
```
  File "/nix/store/gf9vmzyqwyxgf77bsxgsz3zckyhv1pmb-python3-3.6.12-env-patched/lib/python3.6/sysconfig.py", line 421, in _init_posix
    _temp = __import__(name, globals(), locals(), ['build_time_vars'], 0)
ModuleNotFoundError: No module named '_sysconfigdata__linux_x86_64-linux-gnu'

/nix/store/gf9vmzyqwyxgf77bsxgsz3zckyhv1pmb-python3-3.6.12-env-patched/lib/python3.6/_sysconfigdata_m_linux_x86_64-linux-gnu.py
```

I'm not certain this is the cause, but after finding https://github.com/NixOS/nixpkgs/commit/5760e275f4e9469a18e91d4bca1e956f5e777b66 I tried setting mach-nix to `python38` and the private package is now resolving correctly on both platforms.

**Comment by DavHau** [comment]
It seems to me to be an upstream issue for python and they didn't want to backport the fix to python 3.6 because:
`it doesn't hurt Python 3.6.` (see last comment [here](https://bugs.python.org/issue28046))

I remembered running into this issue a while ago and digging a bit. Not sure anymore why it only hurts us and not the upstream maintainers.
I think I won't look into this anymore. It either needs to be fixed in cpython or nixpkgs.
3.6 is EOL after this year anyways.

Oh, just read the title again. Are you sure the problem is also with 3.7? I'd assume not.

**Comment by abathur** [comment]
> I think I won't look into this anymore. It either needs to be fixed in cpython or nixpkgs.
3.6 is EOL after this year anyways.

Ok. I'll go ahead and close.

> Oh, just read the title again. Are you sure the problem is also with 3.7? I'd assume not.

I think you're correct. I did see a failure in CI with 3.7, but I incorrectly assumed it was the same failure--the private package itself does build correctly. I'll update the title.

**Comment by cwhy** [comment]
I have seen the same error on Python3.7
`Traceback (most recent call last):
  File "/nix/store/swspv990j78y9lpzkgyx0hvcmfwdh0is-python3-3.7.10/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/nix/store/swspv990j78y9lpzkgyx0hvcmfwdh0is-python3-3.7.10/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/nix/store/h5pp34jbs854h3c5xfxxssj54as85y7r-python3.7-ipykernel-5.2.1/lib/python3.7/site-packages/ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "/nix/store/h5pp34jbs854h3c5xfxxssj54as85y7r-python3.7-ipykernel-5.2.1/lib/python3.7/site-packages/ipykernel/__init__.py", line 2, in <module>
    from .connect import *
  File "/nix/store/h5pp34jbs854h3c5xfxxssj54as85y7r-python3.7-ipykernel-5.2.1/lib/python3.7/site-packages/ipykernel/connect.py", line 13, in <module>
    from IPython.core.profiledir import ProfileDir
  File "/nix/store/ynw4h5hrnq7sjs0msk0wk81xwwkldx7w-python3.7-ipython-7.13.0/lib/python3.7/site-packages/IPython/__init__.py", line 55, in <module>
    from .core.application import Application
  File "/nix/store/ynw4h5hrnq7sjs0msk0wk81xwwkldx7w-python3.7-ipython-7.13.0/lib/python3.7/site-packages/IPython/core/application.py", line 25, in <module>
    from IPython.core import release, crashhandler
  File "/nix/store/ynw4h5hrnq7sjs0msk0wk81xwwkldx7w-python3.7-ipython-7.13.0/lib/python3.7/site-packages/IPython/core/crashhandler.py", line 27, in <module>
    from IPython.core import ultratb
  File "/nix/store/ynw4h5hrnq7sjs0msk0wk81xwwkldx7w-python3.7-ipython-7.13.0/lib/python3.7/site-packages/IPython/core/ultratb.py", line 97, in <module>
    import pydoc
  File "/nix/store/swspv990j78y9lpzkgyx0hvcmfwdh0is-python3-3.7.10/lib/python3.7/pydoc.py", line 370, in <module>
    class Doc:
  File "/nix/store/swspv990j78y9lpzkgyx0hvcmfwdh0is-python3-3.7.10/lib/python3.7/pydoc.py", line 402, in Doc
    def getdocloc(self, object, basedir=sysconfig.get_path('stdlib')):
  File "/nix/store/swspv990j78y9lpzkgyx0hvcmfwdh0is-python3-3.7.10/lib/python3.7/sysconfig.py", line 513, in get_path
    return get_paths(scheme, vars, expand)[name]
  File "/nix/store/swspv990j78y9lpzkgyx0hvcmfwdh0is-python3-3.7.10/lib/python3.7/sysconfig.py", line 503, in get_paths
    return _expand_vars(scheme, vars)
  File "/nix/store/swspv990j78y9lpzkgyx0hvcmfwdh0is-python3-3.7.10/lib/python3.7/sysconfig.py", line 172, in _expand_vars
    _extend_dict(vars, get_config_vars())
  File "/nix/store/swspv990j78y9lpzkgyx0hvcmfwdh0is-python3-3.7.10/lib/python3.7/sysconfig.py", line 551, in get_config_vars
    _init_posix(_CONFIG_VARS)
  File "/nix/store/swspv990j78y9lpzkgyx0hvcmfwdh0is-python3-3.7.10/lib/python3.7/sysconfig.py", line 422, in _init_posix
    _temp = __import__(name, globals(), locals(), ['build_time_vars'], 0)
ModuleNotFoundError: No module named '_sysconfigdata__linux_x86_64-linux-gnu'
`
