### ISSUE TITLE
Trouble with Httpie and Migra: AttributeError: type object 'Path' has no attribute 'home'

### ISSUE THREAD

**Issue by tad-lispy** [DavHau/mach-nix#254]
Hi! Thank you very much for this tool. 

I'm a novice at both Nix and Python and I hope you can help me to understand what is going on here.

Here is a working `flake.nix`:

```nix
{
  description = "Working environment with httpie";
  inputs.flake-utils.url = "github:numtide/flake-utils";

  outputs = { self, nixpkgs, flake-utils }:
    flake-utils.lib.eachDefaultSystem (system:
      let pkgs = import nixpkgs { inherit system; };
      in
        rec {
          packages.with-httpie = pkgs.stdenv.mkDerivation {
            name = "with-httpie";
            src = self;
            buildInputs = [ pkgs.httpie ];
          };

          defaultPackage = packages.with-httpie;
        }
    );
}
```

with this I can run:

```
$ nix develop
$ http
usage: http [--json] [--form] [--multipart] [--boundary BOUNDARY] [--compress] [--pretty {all,colors,format,none}] [--style STYLE] [--unsorted] [--sorted] [--format-options FORMAT_OPTIONS] [--print WHAT]
            [--headers] [--body] [--verbose] [--all] [--history-print WHAT] [--stream] [--output FILE] [--download] [--continue] [--quiet]
            [--session SESSION_NAME_OR_PATH | --session-read-only SESSION_NAME_OR_PATH] [--auth USER[:PASS]] [--auth-type {basic,digest}] [--ignore-netrc] [--offline] [--proxy PROTOCOL:PROXY_URL] [--follow]
            [--max-redirects MAX_REDIRECTS] [--max-headers MAX_HEADERS] [--timeout SECONDS] [--check-status] [--path-as-is] [--chunked] [--verify VERIFY] [--ssl {ssl2.3,tls1,tls1.1,tls1.2}] [--ciphers CIPHERS]
            [--cert CERT] [--cert-key CERT_KEY] [--ignore-stdin] [--help] [--version] [--traceback] [--default-scheme DEFAULT_SCHEME] [--debug]
            [METHOD] URL [REQUEST_ITEM [REQUEST_ITEM ...]]
http: error: the following arguments are required: URL
```

So it works as expected. Now I want to add a program called Migra (<https://pypi.org/project/migra/>).

```nix
{
  description = "Introducing migra via mach-nix somehow breaks httpie";

  inputs = {
    flake-utils.url = "github:numtide/flake-utils";
    mach-nix = {
      url = "github:DavHau/mach-nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs = { self, nixpkgs, flake-utils, mach-nix }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = import nixpkgs { inherit system; };
        pythonDependencies = mach-nix.lib.${ system }.mkPython {
          requirements = ''
            migra
          '';
        };
      in
        rec {
          packages.with-httpie = pkgs.stdenv.mkDerivation {
            name = "with-httpie";
            src = self;
            buildInputs = [
              pkgs.httpie
              pythonDependencies
            ];
          };

          defaultPackage = packages.with-httpie;
        }
    );
}
```

With the above `migra` works as expected but I can't use `httpie`:

```
$ nix develop
$ migra
usage: migra [-h] [--unsafe] [--schema SCHEMA] [--exclude_schema EXCLUDE_SCHEMA] [--create-extensions-only] [--with-privileges] [--force-utf8] dburl_from dburl_target
migra: error: the following arguments are required: dburl_from, dburl_target
$ http
Traceback (most recent call last):
  File "/nix/store/1ca2gf9as0jzrj4cxlm620fb8c28ylla-httpie-2.4.0/bin/.http-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/1ca2gf9as0jzrj4cxlm620fb8c28ylla-httpie-2.4.0/lib/python3.8/site-packages/httpie/__main__.py", line 10, in main
    from .core import main
  File "/nix/store/1ca2gf9as0jzrj4cxlm620fb8c28ylla-httpie-2.4.0/lib/python3.8/site-packages/httpie/core.py", line 13, in <module>
    from httpie.client import collect_messages
  File "/nix/store/1ca2gf9as0jzrj4cxlm620fb8c28ylla-httpie-2.4.0/lib/python3.8/site-packages/httpie/client.py", line 15, in <module>
    from httpie.plugins.registry import plugin_manager
  File "/nix/store/1ca2gf9as0jzrj4cxlm620fb8c28ylla-httpie-2.4.0/lib/python3.8/site-packages/httpie/plugins/registry.py", line 5, in <module>
    from httpie.output.formatters.colors import ColorFormatter
  File "/nix/store/1ca2gf9as0jzrj4cxlm620fb8c28ylla-httpie-2.4.0/lib/python3.8/site-packages/httpie/output/formatters/colors.py", line 19, in <module>
    from httpie.context import Environment
  File "/nix/store/1ca2gf9as0jzrj4cxlm620fb8c28ylla-httpie-2.4.0/lib/python3.8/site-packages/httpie/context.py", line 13, in <module>
    from httpie.config import DEFAULT_CONFIG_DIR, Config, ConfigFileError
  File "/nix/store/1ca2gf9as0jzrj4cxlm620fb8c28ylla-httpie-2.4.0/lib/python3.8/site-packages/httpie/config.py", line 58, in <module>
    DEFAULT_CONFIG_DIR = get_default_config_dir()
  File "/nix/store/1ca2gf9as0jzrj4cxlm620fb8c28ylla-httpie-2.4.0/lib/python3.8/site-packages/httpie/config.py", line 43, in get_default_config_dir
    home_dir = Path.home()
AttributeError: type object 'Path' has no attribute 'home'
```

I tried adding different PIP packages than Migra (e.g. Numpy) and it didn't break Httpie. I would really like to have both packages available in my project and I'm a bit out of my depth here. Any help will be appreciated.

---

It's probably unrelated issue, but I've noticed that Httpie also doesn't work when installed alone (without Migra) via mach-nix:

```nix
{
  description = "Introducing mach-nix somehow breaks httpie";

  inputs = {
    flake-utils.url = "github:numtide/flake-utils";
    mach-nix = {
      url = "github:DavHau/mach-nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs = { self, nixpkgs, flake-utils, mach-nix }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = import nixpkgs { inherit system; };
        pythonDependencies = mach-nix.lib.${ system }.mkPython {
          requirements = ''
            httpie
          '';
        };
      in
        rec {
          packages.with-httpie = pkgs.stdenv.mkDerivation {
            name = "with-httpie";
            src = self;
            buildInputs = [
              pythonDependencies
            ];
          };

          defaultPackage = packages.with-httpie;
        }
    );
}
```

The error is different now (`ModuleNotFoundError: No module named 'pkg_resources'`)

```
$ nix develop
$ http
Traceback (most recent call last):
  File "/nix/store/m60pkqfr1ksbijpzz7dpp6ngfl5a4hpf-python3.8-httpie-2.4.0/bin/.http-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/l5327cbzcprh5p8fxpwb7bis39qi0ix4-python3-3.8.8-env/lib/python3.8/site-packages/httpie/__main__.py", line 10, in main
    from .core import main
  File "/nix/store/l5327cbzcprh5p8fxpwb7bis39qi0ix4-python3-3.8.8-env/lib/python3.8/site-packages/httpie/core.py", line 13, in <module>
    from httpie.client import collect_messages
  File "/nix/store/l5327cbzcprh5p8fxpwb7bis39qi0ix4-python3-3.8.8-env/lib/python3.8/site-packages/httpie/client.py", line 15, in <module>
    from httpie.plugins.registry import plugin_manager
  File "/nix/store/l5327cbzcprh5p8fxpwb7bis39qi0ix4-python3-3.8.8-env/lib/python3.8/site-packages/httpie/plugins/registry.py", line 1, in <module>
    from httpie.plugins.manager import PluginManager
  File "/nix/store/l5327cbzcprh5p8fxpwb7bis39qi0ix4-python3-3.8.8-env/lib/python3.8/site-packages/httpie/plugins/manager.py", line 5, in <module>
    from pkg_resources import iter_entry_points
ModuleNotFoundError: No module named 'pkg_resources'
```

**Comment by InLaw** [comment]
the python packages (from pypi) works 
`nix-shell -p nixFlakes --run "nix run github:davhau/mach-nix#with.ipython.httpie --show-trace "`

**Comment by DavHau** [comment]
Hey the problem here seems to be that you are trying to use `pkgs.stdenv.mkDerivation` to build your package.
This doesn't work. You're not telling mkDervation how to build the package. Just adding your dependencies via `buildInputs` isn't enough.

But you do not need to use `mkDerivation` at all. Jut use:
```nix
{
  packages.with-httpie = mach-nix.lib."${system}".mkPython {
    requirements = ''
      httpie
      migra
    '';
  };
}
```

Also it looks to me like you might have misunderstood the `nix develop` command. `nix develop` or `nix-shell ./example-file.nix` will not build the given package. These commands are meant for debugging a nix build and will just bring you into the build environment of the given derivation. This mechanism can also be used to assemble an arbitrary shell environment, but then you should use `pkgs.mkShell` to define the shell derivation.
