### ISSUE TITLE
`conda_virtual_packages()` causes installation failures on macOS

### ISSUE THREAD

**Issue by hkailahi** [DavHau/mach-nix#295]
Running `nix-env -if . -A mach-nix` from my Macbook Pro off a [commit from the latest release](https://github.com/DavHau/mach-nix/commit/773580c35bcdb8cbd0820018d304686282f88d16) (pre-`conda-beta` merge) successfully installs `mach-nix`.  The same command fails off the [latest `master` commit](https://github.com/DavHau/mach-nix/commit/77fc01c0e1a92d00d5b8ebeef8fac688a9179350) with the following:
```
$ nix-env -if . -A mach-nix
...
Executing pytestCheckPhase
============================= test session starts ==============================
platform darwin -- Python 3.8.9, pytest-6.2.3, py-1.10.0, pluggy-0.13.1
rootdir: /private/tmp/nix-build-mach-nix-master.drv-0/mach-nix, configfile: pytest.ini, testpaths: mach_nix/tests
collected 296 items / 1 error / 257 deselected / 38 selected

==================================== ERRORS ====================================
______________ ERROR collecting mach_nix/tests/test_providers.py _______________
mach_nix/tests/test_providers.py:3: in <module>
    from mach_nix.data import providers
mach_nix/data/providers.py:521: in <module>
    class CondaDependencyProvider(DependencyProviderBase):
mach_nix/data/providers.py:527: in CondaDependencyProvider
    virtual_packages = conda_virtual_packages()
mach_nix/data/providers.py:503: in conda_virtual_packages
    __glibc=environ.get("MACHNIX_GLIBC_VERSION", platform.libc_ver()[0][1]),
E   IndexError: string index out of range
=============================== warnings summary ===============================
../../../../nix/store/h0dyrnyrlxpfry6khvnbzxd4qnqz19dp-python3.8-conda-4.9.0/lib/python3.8/site-packages/conda/_vendor/auxlib/_vendor/five.py:49
  /nix/store/h0dyrnyrlxpfry6khvnbzxd4qnqz19dp-python3.8-conda-4.9.0/lib/python3.8/site-packages/conda/_vendor/auxlib/_vendor/five.py:49: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    from imp import reload                  # noqa

-- Docs: https://docs.pytest.org/en/stable/warnings.html
=========================== short test summary info ============================
ERROR mach_nix/tests/test_providers.py - IndexError: string index out of range
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
================= 257 deselected, 1 warning, 1 error in 0.55s ==================
builder for '/nix/store/l6z81q9271a286h12yvn6q3jvy89nnr7-mach-nix-master.drv' failed with exit code 2
error: build of '/nix/store/l6z81q9271a286h12yvn6q3jvy89nnr7-mach-nix-master.drv' failed
```
I do not have a `MACHNIX_GLIBC_VERSION` environment variable set on my system, and `platform.libc_ver()` returns an empty tuple.

```
$ nix-shell --run 'python -c "import platform; print(f\"System: {platform.system()}; libc version: {platform.libc_ver()}\")"'
trace: using conda channels: conda-forge, main, r
System: Darwin; libc version: ('', '')
```

---
System info:
```
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-darwin"`
 - host os: `Darwin 19.6.0, macOS 10.15.7`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.12`
 - channels(hkailahi): `"darwin, nixpkgs-21.11pre295944.0747387223e"`
 - nixpkgs: `/Users/hkailahi/.nix-defexpr/channels/nixpkgs`
```

**Comment by hkailahi** [comment]
`nix-env -if . -A mach-nix` successfully completes after commenting out the [following line]( https://github.com/DavHau/mach-nix/blob/master/mach_nix/data/providers.py#L503):
```diff
def conda_virtual_packages():

    packages = dict(
-        __glibc=environ.get("MACHNIX_GLIBC_VERSION", platform.libc_ver()[0][1]),
+        # __glibc=environ.get("MACHNIX_GLIBC_VERSION", platform.libc_ver()[0][1]),
        __unix=0,
    )
```
However this causes failure when I include `conda` as a provider:
```
$ bat ./env-dev/python.nix -r 59:61
───────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: ./env-dev/python.nix
───────┼─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
  59   │ mach-nix.mkPython {
  60   │   requirements = builtins.readFile ./requirements.txt;
  61   │   providers._default = "conda,wheel,sdist,nixpkgs";
───────┴─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
$ nix-shell ./env-dev
building '/nix/store/d0zq4hqxfilwwsgm391phcpr0rx3wqpd-mach_nix_file.drv'...
Traceback (most recent call last):
  File "/nix/store/nykbdrk2wq5gi0248nmzsvjr520j6mhc-dljl5bzw3cvzg0c5vfrmn8z9cnz5rnla-source/mach_nix/generate.py", line 98, in <module>
    main()
  File "/nix/store/nykbdrk2wq5gi0248nmzsvjr520j6mhc-dljl5bzw3cvzg0c5vfrmn8z9cnz5rnla-source/mach_nix/generate.py", line 45, in main
    deps_provider = CombinedDependencyProvider(
  File "/nix/store/nykbdrk2wq5gi0248nmzsvjr520j6mhc-dljl5bzw3cvzg0c5vfrmn8z9cnz5rnla-source/mach_nix/data/providers.py", line 150, in __init__
    raise Exception(f"Error: Unknown providers '{unknown_providers}'. Please remove from 'providers=...'")
Exception: Error: Unknown providers '{'conda'}'. Please remove from 'providers=...'
builder for '/nix/store/d0zq4hqxfilwwsgm391phcpr0rx3wqpd-mach_nix_file.drv' failed with exit code 1
error: build of '/nix/store/d0zq4hqxfilwwsgm391phcpr0rx3wqpd-mach_nix_file.drv' failed
(use '--show-trace' to show detailed location information)
```

**Comment by cideM** [comment]
I have what appears to be the same issue 
```
          foo = mach-nix-utils.mkPythonShell {
            requirements = ''
              pytest==5.4.1
              fastapi==0.63.0
              uvicorn==0.13.3
              boto3==1.12.46
              botocore==1.15.46
              bs4
              requests-html
              html2text
              moto
            '';
          };
```

**Comment by thequicksort** [comment]
@cideM @hkailahi Thanks for reporting this and adding all this information. I think I may have fixed it. Would you like to try it out and let me know if it works for you? 

https://github.com/DavHau/mach-nix/pull/312

**Comment by cideM** [comment]
@thequicksort  I just ran the Nix expression that resulted in the error but with `mach-nix` coming from your fork and I no longer get any errors :medal_military:
