### ISSUE TITLE
Cannot use the cryptography package: No module named 'setuptools_rust'

### ISSUE THREAD

**Issue by pmiddend** [DavHau/mach-nix#305]
I have `cryptography==3.4.7` in my `requirements.txt` which results in this error:

```
Finished cargoSetupPostPatchHook
configuring
no configure script, doing nothing
building
Executing setuptoolsBuildPhase

        =============================DEBUG ASSISTANCE==========================
        If you are seeing an error here please try the following to
        successfully install cryptography:

        Upgrade to the latest pip and try again. This will fix errors for most
        users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
        =============================DEBUG ASSISTANCE==========================
        
Traceback (most recent call last):
  File "nix_run_setup", line 8, in <module>
    exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\\r\\n', '\\n'), __file__, 'exec'))
  File "setup.py", line 14, in <module>
    from setuptools_rust import RustExtension
ModuleNotFoundError: No module named 'setuptools_rust'
builder for '/nix/store/kj5y3d9i4h56rsa69v6dr0cf792lrv4n-python3.8-cryptography-3.4.7.drv' failed with exit code 1
cannot build derivation '/nix/store/cxgf9v895i1ig5l4mzklvp51a54nc36k-python3-3.8.9-env.drv': 1 dependencies couldn't be built
error: build of '/nix/store/cxgf9v895i1ig5l4mzklvp51a54nc36k-python3-3.8.9-env.drv' failed
```

**Comment by TyberiusPrime** [comment]
I can't reproduce this :(

**Comment by ssbothwell** [comment]
I am having the same issue.
