### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by bbtdev** [DavHau/mach-nix#314]
```
$ nix-shell ./env
building '/nix/store/4vkpzlns71i5hfk746yd6yf5r3378i2s-mach_nix_file.drv'...
Traceback (most recent call last):
  File "/nix/store/lqsqmiand28kv5zzcark1dg1pdzi8s0b-python3-3.8.9-env/lib/python3.8/site-packages/resolvelib/resolvers.py", line 185, in _merge_into_criterion
    crit = self.state.criteria[name]
KeyError: 'requests'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/nykbdrk2wq5gi0248nmzsvjr520j6mhc-dljl5bzw3cvzg0c5vfrmn8z9cnz5rnla-source/mach_nix/generate.py", line 98, in <module>
    main()
  File "/nix/store/nykbdrk2wq5gi0248nmzsvjr520j6mhc-dljl5bzw3cvzg0c5vfrmn8z9cnz5rnla-source/mach_nix/generate.py", line 63, in main
    expr = generator.generate(reqs)
  File "/nix/store/nykbdrk2wq5gi0248nmzsvjr520j6mhc-dljl5bzw3cvzg0c5vfrmn8z9cnz5rnla-source/mach_nix/generators/overides_generator.py", line 35, in generate
    pkgs = self.resolver.resolve(reqs)
  File "/nix/store/nykbdrk2wq5gi0248nmzsvjr520j6mhc-dljl5bzw3cvzg0c5vfrmn8z9cnz5rnla-source/mach_nix/resolver/resolvelib_resolver.py", line 63, in resolve
    result = resolvelib.Resolver(Provider(self.nixpkgs, self.deps_provider), reporter).resolve(reqs, max_rounds=1000)
  File "/nix/store/lqsqmiand28kv5zzcark1dg1pdzi8s0b-python3-3.8.9-env/lib/python3.8/site-packages/resolvelib/resolvers.py", line 413, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/nix/store/lqsqmiand28kv5zzcark1dg1pdzi8s0b-python3-3.8.9-env/lib/python3.8/site-packages/resolvelib/resolvers.py", line 280, in resolve
    name, crit = self._merge_into_criterion(r, parent=None)
  File "/nix/store/lqsqmiand28kv5zzcark1dg1pdzi8s0b-python3-3.8.9-env/lib/python3.8/site-packages/resolvelib/resolvers.py", line 187, in _merge_into_criterion
    crit = Criterion.from_requirement(self._p, requirement, parent)
  File "/nix/store/lqsqmiand28kv5zzcark1dg1pdzi8s0b-python3-3.8.9-env/lib/python3.8/site-packages/resolvelib/resolvers.py", line 80, in from_requirement
    candidates = provider.find_matches(requirement)
  File "/nix/store/nykbdrk2wq5gi0248nmzsvjr520j6mhc-dljl5bzw3cvzg0c5vfrmn8z9cnz5rnla-source/mach_nix/resolver/resolvelib_resolver.py", line 42, in find_matches
    matching_versions = filter_versions(all, req.specs)
  File "/nix/store/nykbdrk2wq5gi0248nmzsvjr520j6mhc-dljl5bzw3cvzg0c5vfrmn8z9cnz5rnla-source/mach_nix/cache.py", line 12, in cache_wrapper
    result = func(*args, **kwargs)
  File "/nix/store/nykbdrk2wq5gi0248nmzsvjr520j6mhc-dljl5bzw3cvzg0c5vfrmn8z9cnz5rnla-source/mach_nix/versions.py", line 94, in filter_versions
    versions = list(filter(lambda v: eval(f'v {op} ver', dict(v=v, ver=ver)), versions))
  File "/nix/store/nykbdrk2wq5gi0248nmzsvjr520j6mhc-dljl5bzw3cvzg0c5vfrmn8z9cnz5rnla-source/mach_nix/versions.py", line 94, in <lambda>
    versions = list(filter(lambda v: eval(f'v {op} ver', dict(v=v, ver=ver)), versions))
  File "<string>", line 1
    v === ver
        ^
SyntaxError: invalid syntax
builder for '/nix/store/4vkpzlns71i5hfk746yd6yf5r3378i2s-mach_nix_file.drv' failed with exit code 1
error: build of '/nix/store/4vkpzlns71i5hfk746yd6yf5r3378i2s-mach_nix_file.drv' failed
(use '--show-trace' to show detailed location information)

```

Hey, I'm really dont know how to fix this?

**Comment by DavHau** [comment]
Hey could you tell the parameters which you used to create the ./env ? Which python version, which requirements, etc.
