### ISSUE TITLE
mach-nix removes required dependencies from nixpkgs-package

### ISSUE THREAD

**Issue by DieGoldeneEnte** [DavHau/mach-nix#330]
When trying to install cartopy mach-nix removes all python dependencies, which results in a failed build. I assume the dependencies are removed, because mach-nix can't find the dependencies (which are read from a file in setup.py).

Is there a way disable the removal of dependency for nixpkgs packages or specify the requirements by hand?

output:
```
building '/nix/store/lz28xw33wiks6ra8b2ym46zrbm40zd3x-mach_nix_file.drv'...

### Resolved Dependencies ###

cartopy - 0.20.0 - nixpkgs

Total number of python modules: 1
Removed circular dependencies: 0

trace: removing dependency python3.8-six-1.16.0 from cartopy
trace: removing dependency python3.8-pyshp-2.1.3 from cartopy
trace: removing dependency python3.8-Shapely-1.7.1 from cartopy
trace: removing dependency python3.8-numpy-1.21.2 from cartopy
trace: removing dependency gdal-3.3.2 from cartopy
trace: removing dependency python3.8-Pillow-8.3.2 from cartopy
trace: removing dependency python3.8-matplotlib-3.4.3 from cartopy
trace: removing dependency python3.8-pyepsg-0.4.0 from cartopy
trace: removing dependency python3.8-pykdtree-1.3.4 from cartopy
trace: removing dependency python3.8-scipy-1.7.1 from cartopy
trace: removing dependency python3.8-fiona-1.8.20 from cartopy
trace: removing dependency python3.8-OWSLib-0.25.0 from cartopy
trace: 
applying fix 'add-native-inputs' (nativeBuildInputs) for cartopy:0.20.0

these derivations will be built:
  /nix/store/x41g5c5qyrmz95m65fa625g7db496630-python3.8-cartopy-0.20.0.drv
building '/nix/store/x41g5c5qyrmz95m65fa625g7db496630-python3.8-cartopy-0.20.0.drv'...
Sourcing python-remove-tests-dir-hook
Sourcing python-catch-conflicts-hook.sh
Sourcing python-remove-bin-bytecode-hook.sh
Sourcing setuptools-build-hook
Using setuptoolsBuildPhase
Using setuptoolsShellHook
Sourcing pip-install-hook
Using pipInstallPhase
Sourcing python-imports-check-hook.sh
Using pythonImportsCheckPhase
Sourcing python-namespaces-hook
unpacking sources
unpacking source archive /nix/store/06hbsvrjk1ksr6kv79ayvv29hwh3ins8-Cartopy-0.20.0.tar.gz
source root is Cartopy-0.20.0
setting SOURCE_DATE_EPOCH to timestamp 1631888323 of file Cartopy-0.20.0/setup.cfg
patching sources
configuring
no configure script, doing nothing
building
Executing setuptoolsBuildPhase
Traceback (most recent call last):
  File "setup.py", line 58, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "nix_run_setup", line 8, in <module>
    exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\\r\\n', '\\n'), __file__, 'exec'))
  File "setup.py", line 60, in <module>
    raise ImportError('NumPy 1.10+ is required to install cartopy.')
ImportError: NumPy 1.10+ is required to install cartopy.
builder for '/nix/store/x41g5c5qyrmz95m65fa625g7db496630-python3.8-cartopy-0.20.0.drv' failed with exit code 1
error: build of '/nix/store/x41g5c5qyrmz95m65fa625g7db496630-python3.8-cartopy-0.20.0.drv' failed

```

nix-expr:
```
let

  pkgs = import (builtins.fetchGit {
    name = "nixos-unstable-20210130";
    url = https://github.com/NixOS/nixpkgs/;
    ref = "master";
    rev = "c21ba4f7bb4a3d621eb1d187e6b5e816bb85380c";
  }) {};

  python = "python38";
  pythonPackages = pkgs.${python+"Packages"};

  mach-nix = import (builtins.fetchGit {
    url = "https://github.com/DavHau/mach-nix/";
    ref = "refs/tags/3.3.0";
  }) {
    python = python;
    pkgs = pkgs;
    pypiDataRev = "86593d090eb4753138a501fef60cdfbd2c612e77";
    pypiDataSha256 = "0dfr92vh4fr8cyd5cgicxaa4wy4m53a7nmwbn1352isph2zbp0kk";
  };

in
mach-nix.mkPython {
  requirements = ''
    cartopy
  '';
}
```

**Comment by DieGoldeneEnte** [comment]
Thanks for the tip, though this doesn't seem to work for non-python dependencies (boost is not found when building graph-tool).
My "solution" was to just use a mach-nix version which removes the removal of dependencies, since it only removes required dependencies in my case (line 86 in `mach_nix/generators/overides_generator.py`).

**Comment by DieGoldeneEnte** [comment]
Thanks, didn't have any problems so far with the new version. Really appreciate your work!
