### ISSUE TITLE
resolver - master vs 3.3.0

### ISSUE THREAD

**Issue by InLaw** [DavHau/mach-nix#365]
while 3.3.0 works 
on master it shows:

```
building '/nix/store/9km1byf5figpxv5xlp0b0a446h7aszxh-mach_nix_file.drv'...
Traceback (most recent call last):
  File "/nix/store/zbyrniiw025dlnikabfgx25vcxr546xc-mjvd7hdd3y3i462k1ckvxb1g674sajir-source/mach_nix/generate.py", line 110, in <module>
    main()
  File "/nix/store/zbyrniiw025dlnikabfgx25vcxr546xc-mjvd7hdd3y3i462k1ckvxb1g674sajir-source/mach_nix/generate.py", line 103, in main
    do()
  File "/nix/store/zbyrniiw025dlnikabfgx25vcxr546xc-mjvd7hdd3y3i462k1ckvxb1g674sajir-source/mach_nix/generate.py", line 66, in do
    expr = generator.generate(reqs)
  File "/nix/store/zbyrniiw025dlnikabfgx25vcxr546xc-mjvd7hdd3y3i462k1ckvxb1g674sajir-source/mach_nix/generators/overides_generator.py", line 36, in generate
    pkgs = self.resolver.resolve(reqs)
  File "/nix/store/zbyrniiw025dlnikabfgx25vcxr546xc-mjvd7hdd3y3i462k1ckvxb1g674sajir-source/mach_nix/resolver/resolvelib_resolver.py", line 51, in resolve
    result = resolvelib.Resolver(Provider(self.nixpkgs, self.deps_provider), reporter).resolve(reqs, max_rounds=1000)
  File "/nix/store/1pp3jb452bk19c7v2b7bi0l7fcklkbpc-python3-3.8.5-env/lib/python3.8/site-packages/resolvelib/resolvers.py", line 413, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/nix/store/1pp3jb452bk19c7v2b7bi0l7fcklkbpc-python3-3.8.5-env/lib/python3.8/site-packages/resolvelib/resolvers.py", line 323, in resolve
    raise ResolutionTooDeep(max_rounds)
resolvelib.resolvers.ResolutionTooDeep: 1000
builder for '/nix/store/9km1byf5figpxv5xlp0b0a446h7aszxh-mach_nix_file.drv' failed with exit code 1
error: while evaluating the attribute 'buildInputs' of the derivation 'nix-shell' at /nix/store/xnanigwr38r59b679nxcrp8sjy9g8ij9-nixos-20.09.2344.a3a3dda3bac/nixos/pkgs/build-support/mkshell/default.nix:28:3:
while evaluating the attribute 'passAsFile' of the derivation 'python3-3.8.5-env' at /nix/store/xnanigwr38r59b679nxcrp8sjy9g8ij9-nixos-20.09.2344.a3a3dda3bac/nixos/pkgs/build-support/trivial-builders.nix:7:7:
while evaluating 'callPackageWith' at /nix/store/xnanigwr38r59b679nxcrp8sjy9g8ij9-nixos-20.09.2344.a3a3dda3bac/nixos/lib/customisation.nix:117:35, called from /nix/store/xnanigwr38r59b679nxcrp8sjy9g8ij9-nixos-20.09.2344.a3a3dda3bac/nixos/pkgs/development/interpreters/python/default.nix:20:24:
while evaluating 'makeOverridable' at /nix/store/xnanigwr38r59b679nxcrp8sjy9g8ij9-nixos-20.09.2344.a3a3dda3bac/nixos/lib/customisation.nix:67:24, called from /nix/store/xnanigwr38r59b679nxcrp8sjy9g8ij9-nixos-20.09.2344.a3a3dda3bac/nixos/lib/customisation.nix:121:8:
while evaluating anonymous function at /nix/store/xnanigwr38r59b679nxcrp8sjy9g8ij9-nixos-20.09.2344.a3a3dda3bac/nixos/pkgs/top-level/python-packages.nix:9:1, called from /nix/store/xnanigwr38r59b679nxcrp8sjy9g8ij9-nixos-20.09.2344.a3a3dda3bac/nixos/lib/customisation.nix:69:16:
while evaluating 'fix'' at /nix/store/xnanigwr38r59b679nxcrp8sjy9g8ij9-nixos-20.09.2344.a3a3dda3bac/nixos/lib/fixed-points.nix:25:10, called from /nix/store/xnanigwr38r59b679nxcrp8sjy9g8ij9-nixos-20.09.2344.a3a3dda3bac/nixos/pkgs/top-level/python-packages.nix:7762:4:
while evaluating 'extends' at /nix/store/xnanigwr38r59b679nxcrp8sjy9g8ij9-nixos-20.09.2344.a3a3dda3bac/nixos/lib/fixed-points.nix:69:24, called from /nix/store/xnanigwr38r59b679nxcrp8sjy9g8ij9-nixos-20.09.2344.a3a3dda3bac/nixos/lib/fixed-points.nix:25:21:
while evaluating 'composeExtensions' at /nix/store/xnanigwr38r59b679nxcrp8sjy9g8ij9-nixos-20.09.2344.a3a3dda3bac/nixos/lib/fixed-points.nix:75:17, called from /nix/store/xnanigwr38r59b679nxcrp8sjy9g8ij9-nixos-20.09.2344.a3a3dda3bac/nixos/lib/fixed-points.nix:69:67:
while evaluating 'composeExtensions' at /nix/store/xnanigwr38r59b679nxcrp8sjy9g8ij9-nixos-20.09.2344.a3a3dda3bac/nixos/lib/fixed-points.nix:75:17, called from /nix/store/xnanigwr38r59b679nxcrp8sjy9g8ij9-nixos-20.09.2344.a3a3dda3bac/nixos/lib/fixed-points.nix:76:22:
while evaluating 'composeExtensions' at /nix/store/xnanigwr38r59b679nxcrp8sjy9g8ij9-nixos-20.09.2344.a3a3dda3bac/nixos/lib/fixed-points.nix:75:17, called from /nix/store/xnanigwr38r59b679nxcrp8sjy9g8ij9-nixos-20.09.2344.a3a3dda3bac/nixos/lib/fixed-points.nix:76:22:
while evaluating 'composeExtensions' at /nix/store/xnanigwr38r59b679nxcrp8sjy9g8ij9-nixos-20.09.2344.a3a3dda3bac/nixos/lib/fixed-points.nix:75:17, called from /nix/store/xnanigwr38r59b679nxcrp8sjy9g8ij9-nixos-20.09.2344.a3a3dda3bac/nixos/lib/fixed-points.nix:76:22:
while evaluating 'composeExtensions' at /nix/store/xnanigwr38r59b679nxcrp8sjy9g8ij9-nixos-20.09.2344.a3a3dda3bac/nixos/lib/fixed-points.nix:75:17, called from /nix/store/xnanigwr38r59b679nxcrp8sjy9g8ij9-nixos-20.09.2344.a3a3dda3bac/nixos/lib/fixed-points.nix:76:22:
while evaluating 'composeExtensions' at /nix/store/xnanigwr38r59b679nxcrp8sjy9g8ij9-nixos-20.09.2344.a3a3dda3bac/nixos/lib/fixed-points.nix:75:17, called from /nix/store/xnanigwr38r59b679nxcrp8sjy9g8ij9-nixos-20.09.2344.a3a3dda3bac/nixos/lib/fixed-points.nix:76:22:
while evaluating 'composeExtensions' at /nix/store/xnanigwr38r59b679nxcrp8sjy9g8ij9-nixos-20.09.2344.a3a3dda3bac/nixos/lib/fixed-points.nix:75:17, called from /nix/store/xnanigwr38r59b679nxcrp8sjy9g8ij9-nixos-20.09.2344.a3a3dda3bac/nixos/lib/fixed-points.nix:76:22:
while evaluating 'composeExtensions' at /nix/store/xnanigwr38r59b679nxcrp8sjy9g8ij9-nixos-20.09.2344.a3a3dda3bac/nixos/lib/fixed-points.nix:75:17, called from /nix/store/xnanigwr38r59b679nxcrp8sjy9g8ij9-nixos-20.09.2344.a3a3dda3bac/nixos/lib/fixed-points.nix:76:22:
while evaluating 'composeExtensions' at /nix/store/xnanigwr38r59b679nxcrp8sjy9g8ij9-nixos-20.09.2344.a3a3dda3bac/nixos/lib/fixed-points.nix:75:17, called from /nix/store/xnanigwr38r59b679nxcrp8sjy9g8ij9-nixos-20.09.2344.a3a3dda3bac/nixos/lib/fixed-points.nix:76:22:
while evaluating 'composeExtensions' at /nix/store/xnanigwr38r59b679nxcrp8sjy9g8ij9-nixos-20.09.2344.a3a3dda3bac/nixos/lib/fixed-points.nix:75:17, called from /nix/store/xnanigwr38r59b679nxcrp8sjy9g8ij9-nixos-20.09.2344.a3a3dda3bac/nixos/lib/fixed-points.nix:76:22:
while evaluating 'composeExtensions' at /nix/store/xnanigwr38r59b679nxcrp8sjy9g8ij9-nixos-20.09.2344.a3a3dda3bac/nixos/lib/fixed-points.nix:75:17, called from /nix/store/xnanigwr38r59b679nxcrp8sjy9g8ij9-nixos-20.09.2344.a3a3dda3bac/nixos/lib/fixed-points.nix:76:22:
while evaluating 'composeExtensions' at /nix/store/xnanigwr38r59b679nxcrp8sjy9g8ij9-nixos-20.09.2344.a3a3dda3bac/nixos/lib/fixed-points.nix:75:17, called from /nix/store/xnanigwr38r59b679nxcrp8sjy9g8ij9-nixos-20.09.2344.a3a3dda3bac/nixos/lib/fixed-points.nix:76:22:
while evaluating 'composeExtensions' at /nix/store/xnanigwr38r59b679nxcrp8sjy9g8ij9-nixos-20.09.2344.a3a3dda3bac/nixos/lib/fixed-points.nix:75:17, called from /nix/store/xnanigwr38r59b679nxcrp8sjy9g8ij9-nixos-20.09.2344.a3a3dda3bac/nixos/lib/fixed-points.nix:76:22:
while evaluating 'composeExtensions' at /nix/store/xnanigwr38r59b679nxcrp8sjy9g8ij9-nixos-20.09.2344.a3a3dda3bac/nixos/lib/fixed-points.nix:75:17, called from /nix/store/xnanigwr38r59b679nxcrp8sjy9g8ij9-nixos-20.09.2344.a3a3dda3bac/nixos/lib/fixed-points.nix:76:22:
while evaluating 'composeExtensions' at /nix/store/xnanigwr38r59b679nxcrp8sjy9g8ij9-nixos-20.09.2344.a3a3dda3bac/nixos/lib/fixed-points.nix:75:17, called from /nix/store/xnanigwr38r59b679nxcrp8sjy9g8ij9-nixos-20.09.2344.a3a3dda3bac/nixos/lib/fixed-points.nix:76:22:
while evaluating 'composeExtensions' at /nix/store/xnanigwr38r59b679nxcrp8sjy9g8ij9-nixos-20.09.2344.a3a3dda3bac/nixos/lib/fixed-points.nix:75:17, called from /nix/store/xnanigwr38r59b679nxcrp8sjy9g8ij9-nixos-20.09.2344.a3a3dda3bac/nixos/lib/fixed-points.nix:76:22:
while evaluating 'composeExtensions' at /nix/store/xnanigwr38r59b679nxcrp8sjy9g8ij9-nixos-20.09.2344.a3a3dda3bac/nixos/lib/fixed-points.nix:75:17, called from /nix/store/xnanigwr38r59b679nxcrp8sjy9g8ij9-nixos-20.09.2344.a3a3dda3bac/nixos/lib/fixed-points.nix:76:22:
while evaluating 'composeExtensions' at /nix/store/xnanigwr38r59b679nxcrp8sjy9g8ij9-nixos-20.09.2344.a3a3dda3bac/nixos/lib/fixed-points.nix:75:17, called from /nix/store/xnanigwr38r59b679nxcrp8sjy9g8ij9-nixos-20.09.2344.a3a3dda3bac/nixos/lib/fixed-points.nix:76:22:
while evaluating 'composeExtensions' at /nix/store/xnanigwr38r59b679nxcrp8sjy9g8ij9-nixos-20.09.2344.a3a3dda3bac/nixos/lib/fixed-points.nix:75:17, called from /nix/store/xnanigwr38r59b679nxcrp8sjy9g8ij9-nixos-20.09.2344.a3a3dda3bac/nixos/lib/fixed-points.nix:76:22:
while evaluating 'composeExtensions' at /nix/store/xnanigwr38r59b679nxcrp8sjy9g8ij9-nixos-20.09.2344.a3a3dda3bac/nixos/lib/fixed-points.nix:75:17, called from /nix/store/xnanigwr38r59b679nxcrp8sjy9g8ij9-nixos-20.09.2344.a3a3dda3bac/nixos/lib/fixed-points.nix:76:22:
while evaluating the attribute 'overrides' at /nix/store/mjvd7hdd3y3i462k1ckvxb1g674sajir-source/mach_nix/nix/lib.nix:187:7:
build of '/nix/store/9km1byf5figpxv5xlp0b0a446h7aszxh-mach_nix_file.drv' failed
```

---

how to debug this error?

**Comment by tshaynik** [comment]
I'm running into the same error on master:

```
error: builder for '/nix/store/divi04gqic5sja0g36dxs4m0g1gmyrwx-mach_nix_file.drv' failed with exit code 1;
       last 10 log lines:
       >     expr = generator.generate(reqs)
       >   File "/nix/store/zbyrniiw025dlnikabfgx25vcxr546xc-mjvd7hdd3y3i462k1ckvxb1g674sajir-source/mach_nix/generators/overides_generator.py", line 36, in generate
       >     pkgs = self.resolver.resolve(reqs)
       >   File "/nix/store/zbyrniiw025dlnikabfgx25vcxr546xc-mjvd7hdd3y3i462k1ckvxb1g674sajir-source/mach_nix/resolver/resolvelib_resolver.py", line 51, in resolve
       >     result = resolvelib.Resolver(Provider(self.nixpkgs, self.deps_provider), reporter).resolve(reqs, max_rounds=1000)
       >   File "/nix/store/v1z6skkslfpg9yg79ma2i5zq1m5npl13-python3-3.8.12-env/lib/python3.8/site-packages/resolvelib/resolvers.py", line 413, in resolve
       >     state = resolution.resolve(requirements, max_rounds=max_rounds)
       >   File "/nix/store/v1z6skkslfpg9yg79ma2i5zq1m5npl13-python3-3.8.12-env/lib/python3.8/site-packages/resolvelib/resolvers.py", line 323, in resolve
       >     raise ResolutionTooDeep(max_rounds)
       > resolvelib.resolvers.ResolutionTooDeep: 1000
       For full logs, run 'nix log /nix/store/divi04gqic5sja0g36dxs4m0g1gmyrwx-mach_nix_file.drv'.
(use '--show-trace' to show detailed location information)
```
