### ISSUE TITLE
Sphinx 4.4  on Python 3.7 packetization fails, but no real issues seems to exist

### ISSUE THREAD

**Issue by azazel75** [DavHau/mach-nix#392]
Hello @DavHau, 

I'm having issues creating a Python 3.7 environment with the latest Sphinx, here is the log of the build:

```
$ nix log /nix/store/lq2mzhl5qaa2p0xvd58hbzj40pw2xfns-python3.7-sphinx-4.4.0.drv 

Sourcing python-remove-tests-dir-hook
Sourcing python-catch-conflicts-hook.sh
Sourcing python-remove-bin-bytecode-hook.sh
Sourcing wheel setup hook
Using wheelUnpackPhase
Sourcing pip-install-hook
Using pipInstallPhase
Sourcing python-imports-check-hook.sh
Using pythonImportsCheckPhase
Sourcing python-namespaces-hook
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
Executing wheelUnpackPhase
Finished executing wheelUnpackPhase
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
@nix { "action": "setPhase", "phase": "configurePhase" }
configuring
no configure script, doing nothing
@nix { "action": "setPhase", "phase": "buildPhase" }
building
no Makefile, doing nothing
@nix { "action": "setPhase", "phase": "installPhase" }
installing
Executing pipInstallPhase
/build/dist /build
Processing ./Sphinx-4.4.0-py3-none-any.whl
Requirement already satisfied: babel>=1.3 in /nix/store/84kz3f8k3hhp1gca8nd0yqxa2rnkzqw3-python3.7-babel-2.9.1/lib/python3.7/site-packages (from Sphinx==4.4.0) (2.9.1)

ERROR: Could not find a version that satisfies the requirement importlib-metadata>=4.4; python_version < "3.10" (from sphinx) (from versions: none)
ERROR: No matching distribution found for importlib-metadata>=4.4; python_version < "3.10"
```

Now, [importlib-metadata](https://pypi.org/project/importlib-metadata/#files) is at version 4.10.1 and has both generic sdist and wheel packages, it has a `python_requires` of `>=3.7`.

About mach-nix, it's configured to use latest `pypi-deps-db` package, at commit `da53397f` of 8 hours ago, way more after the release of both the involved packages. Do you have any clue on what's happening and how to debug it further?

**Comment by InLaw** [comment]
https://github.com/DavHau/mach-nix/issues/186

**Comment by DavHau** [comment]
I just tested this on the current version and there doesn't seem to be any issues anymore. Could you check again? If it still doesn't work, could you please provide a flake or other nix expression that reproduces the error? Thanks.

**Comment by azazel75** [comment]
Hi @DavHau, thanks for your work. I finally got the time to test the 3.4.0 release and now I'm getting this traceback:
```
Traceback (most recent call last):
  File "/nix/store/6dr20pzvf1k8y6804dw8q31nj4d7aamz-h88mkfsmnchwn89a3mbgh7d6ixy1di5l-source/mach_nix/generate.py", line 110, in <module>
    main()
  File "/nix/store/6dr20pzvf1k8y6804dw8q31nj4d7aamz-h88mkfsmnchwn89a3mbgh7d6ixy1di5l-source/mach_nix/generate.py", line 103, in main
    do()
  File "/nix/store/6dr20pzvf1k8y6804dw8q31nj4d7aamz-h88mkfsmnchwn89a3mbgh7d6ixy1di5l-source/mach_nix/generate.py", line 66, in do
    expr = generator.generate(reqs)
  File "/nix/store/6dr20pzvf1k8y6804dw8q31nj4d7aamz-h88mkfsmnchwn89a3mbgh7d6ixy1di5l-source/mach_nix/generators/overides_generator.py", line 36, i>
    pkgs = self.resolver.resolve(reqs)
  File "/nix/store/6dr20pzvf1k8y6804dw8q31nj4d7aamz-h88mkfsmnchwn89a3mbgh7d6ixy1di5l-source/mach_nix/resolver/resolvelib_resolver.py", line 83, in>
    remove_circles_and_print(nix_py_pkgs, self.nixpkgs)
  File "/nix/store/6dr20pzvf1k8y6804dw8q31nj4d7aamz-h88mkfsmnchwn89a3mbgh7d6ixy1di5l-source/mach_nix/deptree.py", line 97, in remove_circles_and_p>
    print(format_tree(
  File "/nix/store/2rccadsm49wljm739f57i9vmvf2w6fbs-python3-3.9.6-env/lib/python3.9/site-packages/tree_format/_text.py", line 77, in format_tree
    [format_node(node)],
  File "/nix/store/6dr20pzvf1k8y6804dw8q31nj4d7aamz-h88mkfsmnchwn89a3mbgh7d6ixy1di5l-source/mach_nix/deptree.py", line 78, in name
[machnix.log](https://github.com/DavHau/mach-nix/files/8112657/machnix.log)

    if indexed_pkgs[node_name].build_inputs + indexed_pkgs[node_name].prop_build_inputs == []:
TypeError: unsupported operand type(s) for +: 'NoneType' and 'list'
```

I'll try the master branch before trying to make a smaller example

**Comment by azazel75** [comment]
Master branch works!
