### ISSUE TITLE
buildInputs ignored for buildPythonPackage

### ISSUE THREAD

**Issue by Yajo** [DavHau/mach-nix#411]
With this flake:

```nix
{
  inputs.mach-nix.url = "github:DavHau/mach-nix";
  outputs = {self, nixpkgs, mach-nix}: {
    packages.x86_64-linux.default = mach-nix.lib.x86_64-linux.buildPythonPackage rec {
      python = "python38";

      version = "1.15.1.dev93";

      src = nixpkgs.legacyPackages.x86_64-linux.fetchgit {
        url = "https://github.com/acsone/click-odoo-contrib.git";
        rev = "1.15.1";
        sha256 = "sha256-65wWzIQIwDtEa4f2Sblnw9IteG0M3xaWuu1DbS4k1YI=";
        leaveDotGit = true;
      };

      buildInputs = [nixpkgs.legacyPackages.x86_64-linux.git];

      # HACK https://github.com/DavHau/mach-nix/issues/410
      requirementsExtra = "importlib-resources; python_version < '3.9'";
    };
  };
}
```

<details>
<summary>flake.lock</summary>

```json
{
  "nodes": {
    "flake-utils": {
      "locked": {
        "lastModified": 1642700792,
        "narHash": "sha256-XqHrk7hFb+zBvRg6Ghl+AZDq03ov6OshJLiSWOoX5es=",
        "owner": "numtide",
        "repo": "flake-utils",
        "rev": "846b2ae0fc4cc943637d3d1def4454213e203cba",
        "type": "github"
      },
      "original": {
        "owner": "numtide",
        "repo": "flake-utils",
        "type": "github"
      }
    },
    "mach-nix": {
      "inputs": {
        "flake-utils": "flake-utils",
        "nixpkgs": "nixpkgs",
        "pypi-deps-db": "pypi-deps-db"
      },
      "locked": {
        "lastModified": 1644818395,
        "narHash": "sha256-oU9TcxWjUMdEyB7OajWJ06Lcf0z3HmTl0znMTfIA3dA=",
        "owner": "DavHau",
        "repo": "mach-nix",
        "rev": "c914064c9b8cab9495818ffe8d834d8c2c1d7ce7",
        "type": "github"
      },
      "original": {
        "owner": "DavHau",
        "repo": "mach-nix",
        "type": "github"
      }
    },
    "nixpkgs": {
      "locked": {
        "lastModified": 1643805626,
        "narHash": "sha256-AXLDVMG+UaAGsGSpOtQHPIKB+IZ0KSd9WS77aanGzgc=",
        "owner": "NixOS",
        "repo": "nixpkgs",
        "rev": "554d2d8aa25b6e583575459c297ec23750adb6cb",
        "type": "github"
      },
      "original": {
        "id": "nixpkgs",
        "ref": "nixos-unstable",
        "type": "indirect"
      }
    },
    "nixpkgs_2": {
      "locked": {
        "lastModified": 1647350163,
        "narHash": "sha256-OcMI+PFEHTONthXuEQNddt16Ml7qGvanL3x8QOl2Aao=",
        "owner": "NixOS",
        "repo": "nixpkgs",
        "rev": "3eb07eeafb52bcbf02ce800f032f18d666a9498d",
        "type": "github"
      },
      "original": {
        "id": "nixpkgs",
        "type": "indirect"
      }
    },
    "pypi-deps-db": {
      "flake": false,
      "locked": {
        "lastModified": 1643877077,
        "narHash": "sha256-jv8pIvRFTP919GybOxXE5TfOkrjTbdo9QiCO1TD3ZaY=",
        "owner": "DavHau",
        "repo": "pypi-deps-db",
        "rev": "da53397f0b782b0b18deb72ef8e0fb5aa7c98aa3",
        "type": "github"
      },
      "original": {
        "owner": "DavHau",
        "repo": "pypi-deps-db",
        "type": "github"
      }
    },
    "root": {
      "inputs": {
        "mach-nix": "mach-nix",
        "nixpkgs": "nixpkgs_2"
      }
    }
  },
  "root": "root",
  "version": 7
}
```

</details>

I get this failure:

```sh
> nix build
warning: Git tree '/var/home/yajo/prodevel/nixdoo' is dirty
trace: 
 automatically detected pname: 'click-odoo-contrib'
trace: 
 automatically detected requirements of click-odoo-contrib:1.15.1.dev93 22.05pre-git:
setuptools-scm
click-odoo>=1.3.0


error: builder for '/nix/store/74g5cp4l1rfislp08h7f8hppanqak793-python3.8-click-odoo-contrib-1.15.1.dev93.drv' failed with exit code 1;
       last 10 log lines:
       >     return fn(root, config=config)
       >   File "/nix/store/8biifgjykapvn6m7j0qlklaymb9kich8-python3.8-setuptools-scm-6.4.2/lib/python3.8/site-packages/setuptools_scm/git.py", line 144, in parse
       >     wd = get_working_directory(config)
       >   File "/nix/store/8biifgjykapvn6m7j0qlklaymb9kich8-python3.8-setuptools-scm-6.4.2/lib/python3.8/site-packages/setuptools_scm/git.py", line 129, in get_working_directory
       >     return GitWorkdir.from_potential_worktree(config.parent)
       >   File "/nix/store/8biifgjykapvn6m7j0qlklaymb9kich8-python3.8-setuptools-scm-6.4.2/lib/python3.8/site-packages/setuptools_scm/git.py", line 37, in from_potential_worktree
       >     require_command(cls.COMMAND)
       >   File "/nix/store/8biifgjykapvn6m7j0qlklaymb9kich8-python3.8-setuptools-scm-6.4.2/lib/python3.8/site-packages/setuptools_scm/utils.py", line 137, in require_command
       >     raise OSError("%r was not found" % name)
       > OSError: 'git' was not found
       For full logs, run 'nix log /nix/store/74g5cp4l1rfislp08h7f8hppanqak793-python3.8-click-odoo-contrib-1.15.1.dev93.drv'.
```

<details>
<summary>full logs</summary>

```sh
> nix log /nix/store/74g5cp4l1rfislp08h7f8hppanqak793-python3.8-click-odoo-contrib-1.15.1.dev93.drv | cat
Sourcing python-remove-tests-dir-hook
Sourcing python-catch-conflicts-hook.sh
Sourcing python-remove-bin-bytecode-hook.sh
Sourcing setuptools-build-hook
Using setuptoolsBuildPhase
Using setuptoolsShellHook
Sourcing pip-install-hook
Using pipInstallPhase
Sourcing python-imports-check-hook.sh
Using pythonImportsCheckPhase
Sourcing python-namespaces-hook
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
unpacking source archive /nix/store/9p634cnarkcgdq4pb3ws4k7clmwqdab2-click-odoo-contrib
source root is click-odoo-contrib
setting SOURCE_DATE_EPOCH to timestamp 315619200 of file click-odoo-contrib/tox.ini
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
@nix { "action": "setPhase", "phase": "configurePhase" }
configuring
no configure script, doing nothing
@nix { "action": "setPhase", "phase": "buildPhase" }
building
Executing setuptoolsBuildPhase
Traceback (most recent call last):
  File "nix_run_setup", line 8, in <module>
    exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\\r\\n', '\\n'), __file__, 'exec'))
  File "setup.py", line 10, in <module>
    setup(
  File "/nix/store/7mm2yv11d21ydy59ibk2d2bkj29n6ng0-python3.8-setuptools-57.2.0/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/nix/store/c502m2h2yfqymf9bg4jvvhj038pfimcb-python3-3.8.12/lib/python3.8/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/nix/store/7mm2yv11d21ydy59ibk2d2bkj29n6ng0-python3.8-setuptools-57.2.0/lib/python3.8/site-packages/setuptools/dist.py", line 455, in __init__
    _Distribution.__init__(self, {
  File "/nix/store/c502m2h2yfqymf9bg4jvvhj038pfimcb-python3-3.8.12/lib/python3.8/distutils/dist.py", line 292, in __init__
    self.finalize_options()
  File "/nix/store/7mm2yv11d21ydy59ibk2d2bkj29n6ng0-python3.8-setuptools-57.2.0/lib/python3.8/site-packages/setuptools/dist.py", line 807, in finalize_options
    ep(self)
  File "/nix/store/7mm2yv11d21ydy59ibk2d2bkj29n6ng0-python3.8-setuptools-57.2.0/lib/python3.8/site-packages/setuptools/dist.py", line 814, in _finalize_setup_keywords
    ep.load()(self, ep.name, value)
  File "/nix/store/8biifgjykapvn6m7j0qlklaymb9kich8-python3.8-setuptools-scm-6.4.2/lib/python3.8/site-packages/setuptools_scm/integration.py", line 75, in version_keyword
    _assign_version(dist, config)
  File "/nix/store/8biifgjykapvn6m7j0qlklaymb9kich8-python3.8-setuptools-scm-6.4.2/lib/python3.8/site-packages/setuptools_scm/integration.py", line 48, in _assign_version
    maybe_version = _get_version(config)
  File "/nix/store/8biifgjykapvn6m7j0qlklaymb9kich8-python3.8-setuptools-scm-6.4.2/lib/python3.8/site-packages/setuptools_scm/__init__.py", line 151, in _get_version
    parsed_version = _do_parse(config)
  File "/nix/store/8biifgjykapvn6m7j0qlklaymb9kich8-python3.8-setuptools-scm-6.4.2/lib/python3.8/site-packages/setuptools_scm/__init__.py", line 98, in _do_parse
    version = _version_from_entrypoints(config) or _version_from_entrypoints(
  File "/nix/store/8biifgjykapvn6m7j0qlklaymb9kich8-python3.8-setuptools-scm-6.4.2/lib/python3.8/site-packages/setuptools_scm/_entrypoints.py", line 37, in _version_from_entrypoints
    version: Optional[ScmVersion] = _call_entrypoint_fn(root, config, ep.load())
  File "/nix/store/8biifgjykapvn6m7j0qlklaymb9kich8-python3.8-setuptools-scm-6.4.2/lib/python3.8/site-packages/setuptools_scm/_entrypoints.py", line 13, in _call_entrypoint_fn
    return fn(root, config=config)
  File "/nix/store/8biifgjykapvn6m7j0qlklaymb9kich8-python3.8-setuptools-scm-6.4.2/lib/python3.8/site-packages/setuptools_scm/git.py", line 144, in parse
    wd = get_working_directory(config)
  File "/nix/store/8biifgjykapvn6m7j0qlklaymb9kich8-python3.8-setuptools-scm-6.4.2/lib/python3.8/site-packages/setuptools_scm/git.py", line 129, in get_working_directory
    return GitWorkdir.from_potential_worktree(config.parent)
  File "/nix/store/8biifgjykapvn6m7j0qlklaymb9kich8-python3.8-setuptools-scm-6.4.2/lib/python3.8/site-packages/setuptools_scm/git.py", line 37, in from_potential_worktree
    require_command(cls.COMMAND)
  File "/nix/store/8biifgjykapvn6m7j0qlklaymb9kich8-python3.8-setuptools-scm-6.4.2/lib/python3.8/site-packages/setuptools_scm/utils.py", line 137, in require_command
    raise OSError("%r was not found" % name)
OSError: 'git' was not found
```

</details>

Which means that git is not available at build time, although it was specified as a `buildInput`.

**Comment by bjornfor** [comment]
Could this be a strictDeps thing? Can you try placing it in nativeBuildInputs instead?

**Comment by Yajo** [comment]
That worked. What was happening?

**Comment by bjornfor** [comment]
Technically, buildInputs is for runtime inputs (libraries) and nativeBuildInputs for build-time inputs (build tools). Only build-time inputs get added to PATH. But when strict deps is not set, the two input lists get squashed together in the builder.

The separation between buildInputs and nativeBuildInputs matter for cross-compilation. If you want to know more, see https://matthewbauer.us/blog/beginners-guide-to-cross.html and search for strictDeps here: https://github.com/NixOS/nixpkgs/blob/master/pkgs/stdenv/generic/setup.sh.

**Comment by Yajo** [comment]
Thanks! It seems then that this was just a layer 8 problem. 😁
