### ISSUE TITLE
master # py pkg asttokens - KeyError: 'asttokens' in resolvelib_resolver.py

### ISSUE THREAD

**Issue by InLaw** [DavHau/mach-nix#456]
```
building '/nix/store/rpdmx84r6ds918mpsimw2kk7lrxwgdix-mach_nix_file.drv'...
Multiple nixpkgs attributes found for pip-21.1.3: ['bootstrapped-pip', 'pip']
Picking 'pip' as base attribute name.
Traceback (most recent call last):
  File "/nix/store/6dr20pzvf1k8y6804dw8q31nj4d7aamz-h88mkfsmnchwn89a3mbgh7d6ixy1di5l-source/mach_nix/generate.py", line 110, in <module>
    main()
  File "/nix/store/6dr20pzvf1k8y6804dw8q31nj4d7aamz-h88mkfsmnchwn89a3mbgh7d6ixy1di5l-source/mach_nix/generate.py", line 103, in main
    do()
  File "/nix/store/6dr20pzvf1k8y6804dw8q31nj4d7aamz-h88mkfsmnchwn89a3mbgh7d6ixy1di5l-source/mach_nix/generate.py", line 66, in do
    expr = generator.generate(reqs)
  File "/nix/store/6dr20pzvf1k8y6804dw8q31nj4d7aamz-h88mkfsmnchwn89a3mbgh7d6ixy1di5l-source/mach_nix/generators/overides_generator.py", line 36, in generate
    pkgs = self.resolver.resolve(reqs)
  File "/nix/store/6dr20pzvf1k8y6804dw8q31nj4d7aamz-h88mkfsmnchwn89a3mbgh7d6ixy1di5l-source/mach_nix/resolver/resolvelib_resolver.py", line 60, in resolve
    candidate = result.mapping[name]
KeyError: 'asttokens'
builder for '/nix/store/rpdmx84r6ds918mpsimw2kk7lrxwgdix-mach_nix_file.drv' failed with exit code 1
error: while evaluating the attribute 'buildInputs' of the derivation 'nix-shell' at /nix/store/fx5cnr6jkp6jmv3n8hy7hl5fc86rnjlj-nixos-21.11.337514.4c560cc7ee5/nixos/pkgs/stdenv/generic/make-derivation.nix:205:7:
while evaluating the attribute 'passAsFile' of the derivation 'python3-3.9.12-env' at /nix/store/fx5cnr6jkp6jmv3n8hy7hl5fc86rnjlj-nixos-21.11.337514.4c560cc7ee5/nixos/pkgs/stdenv/generic/make-derivation.nix:205:7:
while evaluating the attribute 'passAsFile' at /nix/store/fx5cnr6jkp6jmv3n8hy7hl5fc86rnjlj-nixos-21.11.337514.4c560cc7ee5/nixos/pkgs/build-support/buildenv/default.nix:77:5:
while evaluating 'callPackageWith' at /nix/store/fx5cnr6jkp6jmv3n8hy7hl5fc86rnjlj-nixos-21.11.337514.4c560cc7ee5/nixos/lib/customisation.nix:117:35, called from /nix/store/fx5cnr6jkp6jmv3n8hy7hl5fc86rnjlj-nixos-21.11.337514.4c560cc7ee5/nixos/pkgs/development/interpreters/python/default.nix:24:24:
while evaluating 'makeOverridable' at /nix/store/fx5cnr6jkp6jmv3n8hy7hl5fc86rnjlj-nixos-21.11.337514.4c560cc7ee5/nixos/lib/customisation.nix:67:24, called from /nix/store/fx5cnr6jkp6jmv3n8hy7hl5fc86rnjlj-nixos-21.11.337514.4c560cc7ee5/nixos/lib/customisation.nix:121:8:
while evaluating anonymous function at /nix/store/fx5cnr6jkp6jmv3n8hy7hl5fc86rnjlj-nixos-21.11.337514.4c560cc7ee5/nixos/pkgs/development/interpreters/python/default.nix:25:10, called from /nix/store/fx5cnr6jkp6jmv3n8hy7hl5fc86rnjlj-nixos-21.11.337514.4c560cc7ee5/nixos/lib/customisation.nix:69:16:
while evaluating 'makeScopeWithSplicing' at /nix/store/fx5cnr6jkp6jmv3n8hy7hl5fc86rnjlj-nixos-21.11.337514.4c560cc7ee5/nixos/lib/customisation.nix:222:80, called from /nix/store/fx5cnr6jkp6jmv3n8hy7hl5fc86rnjlj-nixos-21.11.337514.4c560cc7ee5/nixos/pkgs/development/interpreters/python/default.nix:79:12:
while evaluating 'extends' at /nix/store/fx5cnr6jkp6jmv3n8hy7hl5fc86rnjlj-nixos-21.11.337514.4c560cc7ee5/nixos/lib/fixed-points.nix:69:24, called from /nix/store/fx5cnr6jkp6jmv3n8hy7hl5fc86rnjlj-nixos-21.11.337514.4c560cc7ee5/nixos/lib/customisation.nix:233:14:
while evaluating 'composeExtensions' at /nix/store/fx5cnr6jkp6jmv3n8hy7hl5fc86rnjlj-nixos-21.11.337514.4c560cc7ee5/nixos/lib/fixed-points.nix:75:18, called from /nix/store/fx5cnr6jkp6jmv3n8hy7hl5fc86rnjlj-nixos-21.11.337514.4c560cc7ee5/nixos/lib/fixed-points.nix:69:67:
while evaluating 'composeExtensions' at /nix/store/fx5cnr6jkp6jmv3n8hy7hl5fc86rnjlj-nixos-21.11.337514.4c560cc7ee5/nixos/lib/fixed-points.nix:75:18, called from /nix/store/fx5cnr6jkp6jmv3n8hy7hl5fc86rnjlj-nixos-21.11.337514.4c560cc7ee5/nixos/lib/fixed-points.nix:78:22:
while evaluating 'composeExtensions' at /nix/store/fx5cnr6jkp6jmv3n8hy7hl5fc86rnjlj-nixos-21.11.337514.4c560cc7ee5/nixos/lib/fixed-points.nix:75:18, called from /nix/store/fx5cnr6jkp6jmv3n8hy7hl5fc86rnjlj-nixos-21.11.337514.4c560cc7ee5/nixos/lib/fixed-points.nix:76:22:
while evaluating 'composeExtensions' at /nix/store/fx5cnr6jkp6jmv3n8hy7hl5fc86rnjlj-nixos-21.11.337514.4c560cc7ee5/nixos/lib/fixed-points.nix:75:18, called from /nix/store/fx5cnr6jkp6jmv3n8hy7hl5fc86rnjlj-nixos-21.11.337514.4c560cc7ee5/nixos/lib/fixed-points.nix:76:22:
while evaluating 'composeExtensions' at /nix/store/fx5cnr6jkp6jmv3n8hy7hl5fc86rnjlj-nixos-21.11.337514.4c560cc7ee5/nixos/lib/fixed-points.nix:75:18, called from /nix/store/fx5cnr6jkp6jmv3n8hy7hl5fc86rnjlj-nixos-21.11.337514.4c560cc7ee5/nixos/lib/fixed-points.nix:76:22:
while evaluating 'composeExtensions' at /nix/store/fx5cnr6jkp6jmv3n8hy7hl5fc86rnjlj-nixos-21.11.337514.4c560cc7ee5/nixos/lib/fixed-points.nix:75:18, called from /nix/store/fx5cnr6jkp6jmv3n8hy7hl5fc86rnjlj-nixos-21.11.337514.4c560cc7ee5/nixos/lib/fixed-points.nix:76:22:
while evaluating 'composeExtensions' at /nix/store/fx5cnr6jkp6jmv3n8hy7hl5fc86rnjlj-nixos-21.11.337514.4c560cc7ee5/nixos/lib/fixed-points.nix:75:18, called from /nix/store/fx5cnr6jkp6jmv3n8hy7hl5fc86rnjlj-nixos-21.11.337514.4c560cc7ee5/nixos/lib/fixed-points.nix:76:22:
while evaluating 'composeExtensions' at /nix/store/fx5cnr6jkp6jmv3n8hy7hl5fc86rnjlj-nixos-21.11.337514.4c560cc7ee5/nixos/lib/fixed-points.nix:75:18, called from /nix/store/fx5cnr6jkp6jmv3n8hy7hl5fc86rnjlj-nixos-21.11.337514.4c560cc7ee5/nixos/lib/fixed-points.nix:76:22:
while evaluating 'composeExtensions' at /nix/store/fx5cnr6jkp6jmv3n8hy7hl5fc86rnjlj-nixos-21.11.337514.4c560cc7ee5/nixos/lib/fixed-points.nix:75:18, called from /nix/store/fx5cnr6jkp6jmv3n8hy7hl5fc86rnjlj-nixos-21.11.337514.4c560cc7ee5/nixos/lib/fixed-points.nix:76:22:
while evaluating 'composeExtensions' at /nix/store/fx5cnr6jkp6jmv3n8hy7hl5fc86rnjlj-nixos-21.11.337514.4c560cc7ee5/nixos/lib/fixed-points.nix:75:18, called from /nix/store/fx5cnr6jkp6jmv3n8hy7hl5fc86rnjlj-nixos-21.11.337514.4c560cc7ee5/nixos/lib/fixed-points.nix:76:22:
while evaluating 'composeExtensions' at /nix/store/fx5cnr6jkp6jmv3n8hy7hl5fc86rnjlj-nixos-21.11.337514.4c560cc7ee5/nixos/lib/fixed-points.nix:75:18, called from /nix/store/fx5cnr6jkp6jmv3n8hy7hl5fc86rnjlj-nixos-21.11.337514.4c560cc7ee5/nixos/lib/fixed-points.nix:76:22:
while evaluating 'composeExtensions' at /nix/store/fx5cnr6jkp6jmv3n8hy7hl5fc86rnjlj-nixos-21.11.337514.4c560cc7ee5/nixos/lib/fixed-points.nix:75:18, called from /nix/store/fx5cnr6jkp6jmv3n8hy7hl5fc86rnjlj-nixos-21.11.337514.4c560cc7ee5/nixos/lib/fixed-points.nix:76:22:
while evaluating 'composeExtensions' at /nix/store/fx5cnr6jkp6jmv3n8hy7hl5fc86rnjlj-nixos-21.11.337514.4c560cc7ee5/nixos/lib/fixed-points.nix:75:18, called from /nix/store/fx5cnr6jkp6jmv3n8hy7hl5fc86rnjlj-nixos-21.11.337514.4c560cc7ee5/nixos/lib/fixed-points.nix:76:22:
while evaluating 'composeExtensions' at /nix/store/fx5cnr6jkp6jmv3n8hy7hl5fc86rnjlj-nixos-21.11.337514.4c560cc7ee5/nixos/lib/fixed-points.nix:75:18, called from /nix/store/fx5cnr6jkp6jmv3n8hy7hl5fc86rnjlj-nixos-21.11.337514.4c560cc7ee5/nixos/lib/fixed-points.nix:76:22:
while evaluating 'composeExtensions' at /nix/store/fx5cnr6jkp6jmv3n8hy7hl5fc86rnjlj-nixos-21.11.337514.4c560cc7ee5/nixos/lib/fixed-points.nix:75:18, called from /nix/store/fx5cnr6jkp6jmv3n8hy7hl5fc86rnjlj-nixos-21.11.337514.4c560cc7ee5/nixos/lib/fixed-points.nix:76:22:
while evaluating 'composeExtensions' at /nix/store/fx5cnr6jkp6jmv3n8hy7hl5fc86rnjlj-nixos-21.11.337514.4c560cc7ee5/nixos/lib/fixed-points.nix:75:18, called from /nix/store/fx5cnr6jkp6jmv3n8hy7hl5fc86rnjlj-nixos-21.11.337514.4c560cc7ee5/nixos/lib/fixed-points.nix:76:22:
while evaluating 'composeExtensions' at /nix/store/fx5cnr6jkp6jmv3n8hy7hl5fc86rnjlj-nixos-21.11.337514.4c560cc7ee5/nixos/lib/fixed-points.nix:75:18, called from /nix/store/fx5cnr6jkp6jmv3n8hy7hl5fc86rnjlj-nixos-21.11.337514.4c560cc7ee5/nixos/lib/fixed-points.nix:76:22:
while evaluating 'composeExtensions' at /nix/store/fx5cnr6jkp6jmv3n8hy7hl5fc86rnjlj-nixos-21.11.337514.4c560cc7ee5/nixos/lib/fixed-points.nix:75:18, called from /nix/store/fx5cnr6jkp6jmv3n8hy7hl5fc86rnjlj-nixos-21.11.337514.4c560cc7ee5/nixos/lib/fixed-points.nix:76:22:
while evaluating 'composeExtensions' at /nix/store/fx5cnr6jkp6jmv3n8hy7hl5fc86rnjlj-nixos-21.11.337514.4c560cc7ee5/nixos/lib/fixed-points.nix:75:18, called from /nix/store/fx5cnr6jkp6jmv3n8hy7hl5fc86rnjlj-nixos-21.11.337514.4c560cc7ee5/nixos/lib/fixed-points.nix:76:22:
while evaluating 'composeExtensions' at /nix/store/fx5cnr6jkp6jmv3n8hy7hl5fc86rnjlj-nixos-21.11.337514.4c560cc7ee5/nixos/lib/fixed-points.nix:75:18, called from /nix/store/fx5cnr6jkp6jmv3n8hy7hl5fc86rnjlj-nixos-21.11.337514.4c560cc7ee5/nixos/lib/fixed-points.nix:76:22:
while evaluating the attribute 'overrides' at /nix/store/h88mkfsmnchwn89a3mbgh7d6ixy1di5l-source/mach_nix/nix/lib.nix:187:7:
build of '/nix/store/rpdmx84r6ds918mpsimw2kk7lrxwgdix-mach_nix_file.drv' failed
```

**Comment by blakat360** [comment]
Any ideas on how to solve these 'keyError' errors?
