### ISSUE TITLE
Dots in the python package name seem to break package resolution.

### ISSUE THREAD

**Issue by d6e** [DavHau/mach-nix#46]
This passes fine:
```
let
  machnix = import (
    builtins.fetchGit {
      url = "https://github.com/DavHau/mach-nix/";
      ref = "2.1.0";
    }
  );
in
machnix.mkPython rec {
  requirements = ''
    requests==2.24.0 
  '';
}
```

While this breaks:
```
let
  machnix = import (
    builtins.fetchGit {
      url = "https://github.com/DavHau/mach-nix/";
      ref = "2.1.0";
    }
  );
in
machnix.mkPython rec {
  requirements = ''
    discord.py==1.3.4
  '';
}
```
with this stacktrace:
```
building '/nix/store/z7cpqqvx49icx1k6fwd50fd60d88c4mq-mach_nix_file.drv'...
Traceback (most recent call last):
  File "/nix/store/r06crfb7v84wazad55pysgn6jckv7288-python3-3.7.6-env/lib/python3.7/site-packages/resolvelib/resolvers.py", line 185, in _merge_into_criterion
    crit = self.state.criteria[name]
KeyError: 'discord.py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/r06crfb7v84wazad55pysgn6jckv7288-python3-3.7.6-env/lib/python3.7/site-packages/resolvelib/resolvers.py", line 280, in resolve
    name, crit = self._merge_into_criterion(r, parent=None)
  File "/nix/store/r06crfb7v84wazad55pysgn6jckv7288-python3-3.7.6-env/lib/python3.7/site-packages/resolvelib/resolvers.py", line 187, in _merge_into_criterion
    crit = Criterion.from_requirement(self._p, requirement, parent)
  File "/nix/store/r06crfb7v84wazad55pysgn6jckv7288-python3-3.7.6-env/lib/python3.7/site-packages/resolvelib/resolvers.py", line 87, in from_requirement
    raise RequirementsConflicted(criterion)
resolvelib.resolvers.RequirementsConflicted: Requirements conflict: Requirement.parse('discord.py==1.3.4')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/8a5g856g76h0c7kkvw23i7706q451l85-j82lzp1rgj9jfav9zjb1sgk1gfd8gk99-source/mach_nix/generate.py", line 54, in <module>
    main()
  File "/nix/store/8a5g856g76h0c7kkvw23i7706q451l85-j82lzp1rgj9jfav9zjb1sgk1gfd8gk99-source/mach_nix/generate.py", line 48, in main
    expr = generator.generate(reqs)
  File "/nix/store/8a5g856g76h0c7kkvw23i7706q451l85-j82lzp1rgj9jfav9zjb1sgk1gfd8gk99-source/mach_nix/generators/overlay_generator.py", line 29, in generate
    pkgs = self.resolver.resolve(reqs)
  File "/nix/store/8a5g856g76h0c7kkvw23i7706q451l85-j82lzp1rgj9jfav9zjb1sgk1gfd8gk99-source/mach_nix/resolver/resolvelib_resolver.py", line 62, in resolve
    result = resolvelib.Resolver(Provider(self.nixpkgs, self.deps_provider), reporter).resolve(reqs, max_rounds=1000)
  File "/nix/store/r06crfb7v84wazad55pysgn6jckv7288-python3-3.7.6-env/lib/python3.7/site-packages/resolvelib/resolvers.py", line 413, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/nix/store/r06crfb7v84wazad55pysgn6jckv7288-python3-3.7.6-env/lib/python3.7/site-packages/resolvelib/resolvers.py", line 282, in resolve
    raise ResolutionImpossible(e.criterion.information)
resolvelib.resolvers.ResolutionImpossible: [RequirementInformation(requirement=Requirement.parse('discord.py==1.3.4'), parent=None)]
builder for '/nix/store/z7cpqqvx49icx1k6fwd50fd60d88c4mq-mach_nix_file.drv' failed with exit code 1
```

**Comment by d6e** [comment]
Actually after digging through the code, it wasn't the period that was interfering with resolution after all. Turns out it was because the deps db was out of date. (discord.py==1.3.3 was the newest)

**Comment by DavHau** [comment]
Thanks for reporting. Maybe a better error message should be printed to inform the user if other versions of that package are available and a hint how to manually upgrade the deps db.

**Comment by d6e** [comment]
Yeah, that would be very helpful. Also is there a way to always use the latest deps db?

**Comment by DavHau** [comment]
If you could, then your nix expression would not be reproducible, right? Therefore support for fetching stuff without knowing its hash upfront doesn't really exist in nix. There is at least one manual step necessary to bring the new commit of the DB into the nix expression.
I could imagine the cmdline tool of mach-nix to have a functionality to initialize a mach-nix expression with the latest DB referenced. Something like `mach-nix init` for example.

**Comment by d6e** [comment]
Ahh right, good point. Still new to nix.
