### ISSUE TITLE
Many packages causing `No module named 'flit_core'` error

### ISSUE THREAD

**Issue by adamlwgriffiths** [DavHau/mach-nix#461]
With mach-nix 3.5.0, when trying to install packages like `fastapi`, I get the following error:
```
ModuleNotFoundError: No module named 'flit_core'
```

<details>

<summary>Full error</summary>

```
building '/nix/store/piva1g54zyhppn9jcvz1fm76kz6mrr0x-mach_nix_file.drv'...
Multiple nixpkgs attributes found for setuptools-scm-6.3.2: ['setuptools-scm', 'setuptools_scm']
Picking 'setuptools-scm' as base attribute name.
direnv: ([/nix/store/6awyrp3v99qndmy5m0k4bdd6xxkn896q-direnv-2.29.0/bin/direnv export bash]) is taking a while to execute. Use CTRL-C to give up.

### Resolved Dependencies ###

fastapi - 0.73.0 - nixpkgs (attrs: fastapi)
├── starlette - 0.17.1 - nixpkgs (attrs: starlette)
│   └── anyio - 3.3.4 - nixpkgs (attrs: anyio)
│       ├── sniffio - 1.2.0 - nixpkgs (attrs: sniffio)
│       ├── setuptools-scm - 6.3.2 - nixpkgs (attrs: setuptools-scm setuptools_scm)
│       │   ├── tomli - 1.2.2 - nixpkgs (attrs: tomli)
│       │   ├── setuptools - 57.2.0 - nixpkgs (attrs: setuptools)
│       │   └── packaging - 21.3 - nixpkgs (attrs: packaging)
│       │       └── pyparsing - 2.4.7 - nixpkgs (attrs: pyparsing)
│       └── idna - 3.3 - nixpkgs (attrs: idna)
└── pydantic - 1.9.0 - nixpkgs (attrs: pydantic)
    └── typing-extensions - 4.0.1 - nixpkgs (attrs: typing-extensions)

Total number of python modules: 12
Removed circular dependencies: 0

trace: removing dependency python3.9-aiofiles-0.8.0 from starlette
trace: removing dependency python3.9-six-1.16.0 from packaging
trace: removing dependency python3.9-flit-core-3.6.0 from tomli
trace: removing dependency python3.9-itsdangerous-2.0.1 from starlette
trace: removing dependency python3.9-Jinja2-3.0.3 from starlette
trace: removing dependency python3.9-python-multipart-0.0.5 from starlette
trace: removing dependency python3.9-PyYAML-6.0 from starlette
trace: removing dependency python3.9-requests-2.26.0 from starlette
trace: removing dependency python3.9-email-validator-1.1.3 from pydantic
trace: removing dependency python3.9-python-dotenv-0.19.2 from pydantic
trace: removing dependency python3.9-flit-core-3.6.0 from typing-extensions
trace: removing dependency python3.9-ujson-4.3.0 from pydantic
these derivations will be built:
  /nix/store/wzyd4q1klrz1iczb0r7acfyvnc6szr5d-python3.9-typing-extensions-4.0.1.drv
  /nix/store/dr9ml3fjqsvzq4m6c821in0p2xd58rbn-python3.9-pydantic-1.9.0.drv
  /nix/store/kdn69r35k8gl0pi893n4088djz0da3yw-python3.9-tomli-1.2.2.drv
  /nix/store/x8ylgw0m0jyx7apx1h9ymsiwh8gxmdrc-python3.9-setuptools-scm-6.3.2.drv
  /nix/store/m2j0d20ikzcsbiwwkg3il5jyrwp2l1mf-python3.9-anyio-3.3.4.drv
  /nix/store/mz8vxnpzlgbghpvrlxzbsd03s8rhryfz-python3.9-starlette-0.17.1.drv
  /nix/store/shnk42zkd1l2r2zzxrg5k703hkkidq58-python3.9-fastapi-0.73.0.drv
  /nix/store/l6ni1fclcsz4qacpnjzagc5rrmc41sa8-python3-3.9.9-env.drv
  /nix/store/zn83hl034w4aafb03iiv3gd34xd7kaj2-python3-3.9.9-env.drv
building '/nix/store/wzyd4q1klrz1iczb0r7acfyvnc6szr5d-python3.9-typing-extensions-4.0.1.drv'...
building '/nix/store/kdn69r35k8gl0pi893n4088djz0da3yw-python3.9-tomli-1.2.2.drv'...
Sourcing python-remove-tests-dir-hook
Sourcing python-catch-conflicts-hook.sh
Sourcing python-remove-bin-bytecode-hook.sh
Sourcing pip-build-hook
Using pipBuildPhase
Using pipShellHook
Sourcing pip-install-hook
Using pipInstallPhase
Sourcing python-imports-check-hook.sh
Using pythonImportsCheckPhase
Sourcing python-namespaces-hook
Sourcing python-remove-tests-dir-hook
Sourcing python-catch-conflicts-hook.sh
Sourcing python-remove-bin-bytecode-hook.sh
Sourcing pip-build-hook
Using pipBuildPhase
Using pipShellHook
Sourcing pip-install-hook
Using pipInstallPhase
Sourcing python-imports-check-hook.sh
Using pythonImportsCheckPhase
Sourcing python-namespaces-hook
unpacking sources
unpacking source archive /nix/store/9j9yv6726566814n7kbky57k99p761z3-typing_extensions-4.0.1.tar.gz
source root is typing_extensions-4.0.1
setting SOURCE_DATE_EPOCH to timestamp 1638322631 of file typing_extensions-4.0.1/pyproject.toml
patching sources
unpacking sources
unpacking source archive /nix/store/18x00x3kijmkyzbiq6mkmhwfvfapsir4-source
configuring
no configure script, doing nothing
building
Executing pipBuildPhase
Creating a wheel...
source root is source
setting SOURCE_DATE_EPOCH to timestamp 315619200 of file source/tomli/py.typed
patching sources
applying patch /nix/store/6wprwrjrrxnqfpab3cgjc5cgm247pwla-fix-backwards-compatibility-load.patch
patching file tomli/_parser.py
configuring
no configure script, doing nothing
building
Executing pipBuildPhase
Creating a wheel...
WARNING: The directory '/homeless-shelter/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
Processing /build/typing_extensions-4.0.1
  Running command /nix/store/x24kxyqwqg2ln8kh9ky342kdcmhbng3h-python3-3.9.9/bin/python3.9 /nix/store/x74p4bh3ayxsk3k82a8dkbgjsgklps5q-python3.9-pip-21.3.1/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /build/tmpyxcladen
WARNING: The directory '/homeless-shelter/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
  Preparing metadata (pyproject.toml) ... done
ERROR: Exception:
Traceback (most recent call last):
  File "/nix/store/x74p4bh3ayxsk3k82a8dkbgjsgklps5q-python3.9-pip-21.3.1/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 164, in exc_logging_wrapper
    status = run_func(*args)
  File "/nix/store/x74p4bh3ayxsk3k82a8dkbgjsgklps5q-python3.9-pip-21.3.1/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "/nix/store/x74p4bh3ayxsk3k82a8dkbgjsgklps5q-python3.9-pip-21.3.1/lib/python3.9/site-packages/pip/_internal/commands/wheel.py", line 144, in run
    requirement_set = resolver.resolve(reqs, check_supported_wheels=True)
  File "/nix/store/x74p4bh3ayxsk3k82a8dkbgjsgklps5q-python3.9-pip-21.3.1/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 73, in resolve
    collected = self.factory.collect_root_requirements(root_reqs)
  File "/nix/store/x74p4bh3ayxsk3k82a8dkbgjsgklps5q-python3.9-pip-21.3.1/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 468, in collect_root_requirements
    req = self._make_requirement_from_install_req(
  File "/nix/store/x74p4bh3ayxsk3k82a8dkbgjsgklps5q-python3.9-pip-21.3.1/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 430, in _make_requirement_from_install_req
    cand = self._make_candidate_from_link(
  File "/nix/store/x74p4bh3ayxsk3k82a8dkbgjsgklps5q-python3.9-pip-21.3.1/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 201, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "/nix/store/x74p4bh3ayxsk3k82a8dkbgjsgklps5q-python3.9-pip-21.3.1/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 281, in __init__
    super().__init__(
  File "/nix/store/x74p4bh3ayxsk3k82a8dkbgjsgklps5q-python3.9-pip-21.3.1/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 156, in __init__
    self.dist = self._prepare()
  File "/nix/store/x74p4bh3ayxsk3k82a8dkbgjsgklps5q-python3.9-pip-21.3.1/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 225, in _prepare
    dist = self._prepare_distribution()
  File "/nix/store/x74p4bh3ayxsk3k82a8dkbgjsgklps5q-python3.9-pip-21.3.1/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 292, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "/nix/store/x74p4bh3ayxsk3k82a8dkbgjsgklps5q-python3.9-pip-21.3.1/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 482, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/nix/store/x74p4bh3ayxsk3k82a8dkbgjsgklps5q-python3.9-pip-21.3.1/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 546, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
  File "/nix/store/x74p4bh3ayxsk3k82a8dkbgjsgklps5q-python3.9-pip-21.3.1/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 58, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "/nix/store/x74p4bh3ayxsk3k82a8dkbgjsgklps5q-python3.9-pip-21.3.1/lib/python3.9/site-packages/pip/_internal/distributions/sdist.py", line 49, in prepare_distribution_metadata
    self.req.prepare_metadata()
  File "/nix/store/x74p4bh3ayxsk3k82a8dkbgjsgklps5q-python3.9-pip-21.3.1/lib/python3.9/site-packages/pip/_internal/req/req_install.py", line 556, in prepare_metadata
    self.metadata_directory = generate_metadata(
  File "/nix/store/x74p4bh3ayxsk3k82a8dkbgjsgklps5q-python3.9-pip-21.3.1/lib/python3.9/site-packages/pip/_internal/operations/build/metadata.py", line 28, in generate_metadata
    distinfo_dir = backend.prepare_metadata_for_build_wheel(metadata_dir)
  File "/nix/store/x74p4bh3ayxsk3k82a8dkbgjsgklps5q-python3.9-pip-21.3.1/lib/python3.9/site-packages/pip/_vendor/pep517/wrappers.py", line 188, in prepare_metadata_for_build_wheel
    return self._call_hook('prepare_metadata_for_build_wheel', {
  File "/nix/store/x74p4bh3ayxsk3k82a8dkbgjsgklps5q-python3.9-pip-21.3.1/lib/python3.9/site-packages/pip/_vendor/pep517/wrappers.py", line 332, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
pip._vendor.pep517.wrappers.BackendUnavailable: Traceback (most recent call last):
  File "/nix/store/x74p4bh3ayxsk3k82a8dkbgjsgklps5q-python3.9-pip-21.3.1/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 89, in _build_backend
    obj = import_module(mod_path)
  File "/nix/store/x24kxyqwqg2ln8kh9ky342kdcmhbng3h-python3-3.9.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'flit_core'

Processing /build/source
  Running command /nix/store/x24kxyqwqg2ln8kh9ky342kdcmhbng3h-python3-3.9.9/bin/python3.9 /nix/store/x74p4bh3ayxsk3k82a8dkbgjsgklps5q-python3.9-pip-21.3.1/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /build/tmptnxxgrsu
  Preparing metadata (pyproject.toml) ... done
ERROR: Exception:
Traceback (most recent call last):
  File "/nix/store/x74p4bh3ayxsk3k82a8dkbgjsgklps5q-python3.9-pip-21.3.1/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 164, in exc_logging_wrapper
    status = run_func(*args)
  File "/nix/store/x74p4bh3ayxsk3k82a8dkbgjsgklps5q-python3.9-pip-21.3.1/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "/nix/store/x74p4bh3ayxsk3k82a8dkbgjsgklps5q-python3.9-pip-21.3.1/lib/python3.9/site-packages/pip/_internal/commands/wheel.py", line 144, in run
    requirement_set = resolver.resolve(reqs, check_supported_wheels=True)
  File "/nix/store/x74p4bh3ayxsk3k82a8dkbgjsgklps5q-python3.9-pip-21.3.1/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 73, in resolve
    collected = self.factory.collect_root_requirements(root_reqs)
  File "/nix/store/x74p4bh3ayxsk3k82a8dkbgjsgklps5q-python3.9-pip-21.3.1/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 468, in collect_root_requirements
    req = self._make_requirement_from_install_req(
  File "/nix/store/x74p4bh3ayxsk3k82a8dkbgjsgklps5q-python3.9-pip-21.3.1/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 430, in _make_requirement_from_install_req
    cand = self._make_candidate_from_link(
  File "/nix/store/x74p4bh3ayxsk3k82a8dkbgjsgklps5q-python3.9-pip-21.3.1/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 201, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "/nix/store/x74p4bh3ayxsk3k82a8dkbgjsgklps5q-python3.9-pip-21.3.1/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 281, in __init__
    super().__init__(
  File "/nix/store/x74p4bh3ayxsk3k82a8dkbgjsgklps5q-python3.9-pip-21.3.1/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 156, in __init__
    self.dist = self._prepare()
  File "/nix/store/x74p4bh3ayxsk3k82a8dkbgjsgklps5q-python3.9-pip-21.3.1/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 225, in _prepare
    dist = self._prepare_distribution()
  File "/nix/store/x74p4bh3ayxsk3k82a8dkbgjsgklps5q-python3.9-pip-21.3.1/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 292, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "/nix/store/x74p4bh3ayxsk3k82a8dkbgjsgklps5q-python3.9-pip-21.3.1/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 482, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/nix/store/x74p4bh3ayxsk3k82a8dkbgjsgklps5q-python3.9-pip-21.3.1/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 546, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
  File "/nix/store/x74p4bh3ayxsk3k82a8dkbgjsgklps5q-python3.9-pip-21.3.1/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 58, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "/nix/store/x74p4bh3ayxsk3k82a8dkbgjsgklps5q-python3.9-pip-21.3.1/lib/python3.9/site-packages/pip/_internal/distributions/sdist.py", line 49, in prepare_distribution_metadata
    self.req.prepare_metadata()
  File "/nix/store/x74p4bh3ayxsk3k82a8dkbgjsgklps5q-python3.9-pip-21.3.1/lib/python3.9/site-packages/pip/_internal/req/req_install.py", line 556, in prepare_metadata
    self.metadata_directory = generate_metadata(
  File "/nix/store/x74p4bh3ayxsk3k82a8dkbgjsgklps5q-python3.9-pip-21.3.1/lib/python3.9/site-packages/pip/_internal/operations/build/metadata.py", line 28, in generate_metadata
    distinfo_dir = backend.prepare_metadata_for_build_wheel(metadata_dir)
  File "/nix/store/x74p4bh3ayxsk3k82a8dkbgjsgklps5q-python3.9-pip-21.3.1/lib/python3.9/site-packages/pip/_vendor/pep517/wrappers.py", line 188, in prepare_metadata_for_build_wheel
    return self._call_hook('prepare_metadata_for_build_wheel', {
  File "/nix/store/x74p4bh3ayxsk3k82a8dkbgjsgklps5q-python3.9-pip-21.3.1/lib/python3.9/site-packages/pip/_vendor/pep517/wrappers.py", line 332, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
pip._vendor.pep517.wrappers.BackendUnavailable: Traceback (most recent call last):
  File "/nix/store/x74p4bh3ayxsk3k82a8dkbgjsgklps5q-python3.9-pip-21.3.1/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 89, in _build_backend
    obj = import_module(mod_path)
  File "/nix/store/x24kxyqwqg2ln8kh9ky342kdcmhbng3h-python3-3.9.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'flit_core'

builder for '/nix/store/wzyd4q1klrz1iczb0r7acfyvnc6szr5d-python3.9-typing-extensions-4.0.1.drv' failed with exit code 2
cannot build derivation '/nix/store/zn83hl034w4aafb03iiv3gd34xd7kaj2-python3-3.9.9-env.drv': 1 dependencies couldn't be built
error: build of '/nix/store/zn83hl034w4aafb03iiv3gd34xd7kaj2-python3-3.9.9-env.drv' failed
```

</details>

<details>

<summary>shell.nix</summary>

```
{ pkgs ? import <nixpkgs> {} }:

let
  # https://github.com/DavHau/pypi-deps-db
  # commit: 0f6802c48c6cc07566d7628801ba17a46a175f07
  # Wed Jun 8 20:41:22 UTC 2022
  pypiDataRev="0f6802c48c6cc07566d7628801ba17a46a175f07";
  # this hash is wrong but mach doesn't care?!
  pypiDataSha256="14mjsyybw4bmrn35970hdq9ikw1951hqwvbbv24ij3csdrvbcvhb";
  mach-nix = import (builtins.fetchGit {
    url = "https://github.com/DavHau/mach-nix";
    ref = "3.5.0";
  }) {
    inherit pypiDataRev pypiDataSha256;
  };
  pkgs =  mach-nix.nixpkgs;

  custom-python = mach-nix.mkPython {
    python = "python39";
    requirements = ''
      fastapi
    '';
    providers = {
      _default = "nixpkgs,wheel,sdist";
    };
  };
in pkgs.mkShell {
  buildInputs = with pkgs; [
    custom-python
  ];

  shellHook = ''
    export PYTHONDONTWRITEBYTECODE=1
  '';
}

```
</details>

**Comment by knl** [comment]
I'm also seeing the same error. For me, it was for `tomli`, so I added override for it:

```nix
mach-nix.mkPythonShell {
  python = "python310";
  requirements = builtins.readFile ./requirements.txt;
  _.tomli.propagatedBuildInputs.mod = pySelf: self: oldVal: oldVal ++ [ pySelf.flit-core ];
}
```
