### ISSUE TITLE
Distlib issue after update

### ISSUE THREAD

**Issue by gador** [DavHau/mach-nix#524]
After the update from PR #522 in commit 913e6c16f986746ba5507878ef7ff992804d1fa8 I get the following error message when building my system:

```
error: build of '/nix/store/bv300766kfa298cdh6k62fmblrcn8igi-python3.9-distlib-0.3.7.dev.0.drv' on 'ssh://logi-nixos' failed: builder for '/nix/store/bv300766kfa298cdh6k62fmblrcn8igi-python3.9-distlib-0.3.7.dev.0.drv' failed with exit code 2
error: builder for '/nix/store/bv300766kfa298cdh6k62fmblrcn8igi-python3.9-distlib-0.3.7.dev.0.drv' failed with exit code 1;
       last 10 log lines:
       >   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
       >   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
       >   File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
       >   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
       >   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
       >   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
       >   File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
       > ModuleNotFoundError: No module named 'setuptools'
       >
       >
       For full logs, run 'nix log /nix/store/bv300766kfa298cdh6k62fmblrcn8igi-python3.9-distlib-0.3.7.dev.0.drv'.
error: 1 dependencies of derivation '/nix/store/55s2mwpj4pi3ahl1j9ngdv5h16fmqhws-mach-nix-master.drv' failed to build
error: 1 dependencies of derivation '/nix/store/1lk8gfcw3x4qpq9wgqhdychrs216h7bk-home-manager-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/x8lhmnggnhp2xa0gpcc298vdycqmidfn-home-manager-generation.drv' failed to build
```

The error from the `nix log` is:

```
nix log /nix/store/bv300766kfa298cdh6k62fmblrcn8igi-python3.9-distlib-0.3.7.dev.0.drv
Sourcing python-remove-tests-dir-hook
Sourcing python-catch-conflicts-hook.sh
Sourcing python-remove-bin-bytecode-hook.sh
Sourcing pip-build-hook
Using pipBuildPhase
Using pipShellHook
Sourcing pip-install-hook
Using pipInstallPhase
Sourcing python-imports-check-hook.sh
Using pythonImportsCheckPhase
Sourcing python-namespaces-hook
Sourcing python-catch-conflicts-hook.sh
unpacking sources
unpacking source archive /nix/store/ibrcwzm3wikip0v049ilxfjifwamr2ma-61534987ec5e4b3bdd346de8ffcc7aeaeb132572.zip
source root is distlib-61534987ec5e4b3bdd346de8ffcc7aeaeb132572
setting SOURCE_DATE_EPOCH to timestamp 1667246889 of file distlib-61534987ec5e4b3bdd346de8ffcc7aeaeb132572/tox.ini
patching sources
configuring
no configure script, doing nothing
building
Executing pipBuildPhase
Creating a wheel...
WARNING: The directory '/homeless-shelter/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. I>
Processing /build/distlib-61534987ec5e4b3bdd346de8ffcc7aeaeb132572
  Running command Preparing metadata (pyproject.toml)
  Preparing metadata (pyproject.toml) ... done
ERROR: Exception:
Traceback (most recent call last):
  File "/nix/store/pcy2yfimk1zmjskbss67yair10v3dhid-python3.9-pip-22.2.2/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 167, in exc_logging_wrapper
    status = run_func(*args)
  File "/nix/store/pcy2yfimk1zmjskbss67yair10v3dhid-python3.9-pip-22.2.2/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 247, in wrapper
    return func(self, options, args)
  File "/nix/store/pcy2yfimk1zmjskbss67yair10v3dhid-python3.9-pip-22.2.2/lib/python3.9/site-packages/pip/_internal/commands/wheel.py", line 145, in run
    requirement_set = resolver.resolve(reqs, check_supported_wheels=True)
  File "/nix/store/pcy2yfimk1zmjskbss67yair10v3dhid-python3.9-pip-22.2.2/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 73, in resolve
    collected = self.factory.collect_root_requirements(root_reqs)
  File "/nix/store/pcy2yfimk1zmjskbss67yair10v3dhid-python3.9-pip-22.2.2/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 491, in collect_root_requirements
    req = self._make_requirement_from_install_req(
  File "/nix/store/pcy2yfimk1zmjskbss67yair10v3dhid-python3.9-pip-22.2.2/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 453, in _make_requirement_from_install_req
    cand = self._make_candidate_from_link(
  File "/nix/store/pcy2yfimk1zmjskbss67yair10v3dhid-python3.9-pip-22.2.2/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 206, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "/nix/store/pcy2yfimk1zmjskbss67yair10v3dhid-python3.9-pip-22.2.2/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 297, in __init__
    super().__init__(
  File "/nix/store/pcy2yfimk1zmjskbss67yair10v3dhid-python3.9-pip-22.2.2/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 162, in __init__
    self.dist = self._prepare()
  File "/nix/store/pcy2yfimk1zmjskbss67yair10v3dhid-python3.9-pip-22.2.2/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 231, in _prepare
    dist = self._prepare_distribution()
  File "/nix/store/pcy2yfimk1zmjskbss67yair10v3dhid-python3.9-pip-22.2.2/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 308, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "/nix/store/pcy2yfimk1zmjskbss67yair10v3dhid-python3.9-pip-22.2.2/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 438, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/nix/store/pcy2yfimk1zmjskbss67yair10v3dhid-python3.9-pip-22.2.2/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 524, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
  File "/nix/store/pcy2yfimk1zmjskbss67yair10v3dhid-python3.9-pip-22.2.2/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 68, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(
  File "/nix/store/pcy2yfimk1zmjskbss67yair10v3dhid-python3.9-pip-22.2.2/lib/python3.9/site-packages/pip/_internal/distributions/sdist.py", line 61, in prepare_distribution_metadata
    self.req.prepare_metadata()
  File "/nix/store/pcy2yfimk1zmjskbss67yair10v3dhid-python3.9-pip-22.2.2/lib/python3.9/site-packages/pip/_internal/req/req_install.py", line 533, in prepare_metadata
    self.metadata_directory = generate_metadata(
  File "/nix/store/pcy2yfimk1zmjskbss67yair10v3dhid-python3.9-pip-22.2.2/lib/python3.9/site-packages/pip/_internal/operations/build/metadata.py", line 35, in generate_metadata
    distinfo_dir = backend.prepare_metadata_for_build_wheel(metadata_dir)
  File "/nix/store/pcy2yfimk1zmjskbss67yair10v3dhid-python3.9-pip-22.2.2/lib/python3.9/site-packages/pip/_internal/utils/misc.py", line 706, in prepare_metadata_for_build_wheel
    return super().prepare_metadata_for_build_wheel(
  File "/nix/store/pcy2yfimk1zmjskbss67yair10v3dhid-python3.9-pip-22.2.2/lib/python3.9/site-packages/pip/_vendor/pep517/wrappers.py", line 188, in prepare_metadata_for_build_wheel
    return self._call_hook('prepare_metadata_for_build_wheel', {
  File "/nix/store/pcy2yfimk1zmjskbss67yair10v3dhid-python3.9-pip-22.2.2/lib/python3.9/site-packages/pip/_vendor/pep517/wrappers.py", line 332, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
pip._vendor.pep517.wrappers.BackendUnavailable: Traceback (most recent call last):
  File "/nix/store/pcy2yfimk1zmjskbss67yair10v3dhid-python3.9-pip-22.2.2/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 89, in _build_backend
    obj = import_module(mod_path)
  File "/nix/store/k8y99c7fg9dc7mm358cchnv9fk4cw5ll-python3-3.9.15/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'setuptools'
```
When pinning to 65266b5cc867fec2cb6a25409dd7cd12251f6107 mach-nix builds. This is before the 0.3.6 version bump introduced in fac3e3c45729ec313cc711af04c25e96df744195 (which also fails to build)

**Comment by nhatanh-zen8** [comment]
I'm getting the same issue after the distlib update PR was merged:
```
error: builder for '/nix/store/wzhaijv9a1p3a0w30pqcdnwg2fkp5zfl-python3.9-distlib-0.3.7.dev.0.drv' failed with exit code 2;
       last 10 log lines:
       >   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
       >   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
       >   File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
       >   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
       >   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
       >   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
       >   File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
       > ModuleNotFoundError: No module named 'setuptools'
       >
       >
       For full logs, run 'nix log /nix/store/wzhaijv9a1p3a0w30pqcdnwg2fkp5zfl-python3.9-distlib-0.3.7.dev.0.drv'.
error: 1 dependencies of derivation '/nix/store/dymzih5ljhg9gf23cvdasln8xl968ryc-mach-nix-master.drv' failed to build
```

**Comment by luciusmagn** [comment]
I am having the same issue exactly

**Comment by TyberiusPrime** [comment]
Can y'all check the current master - I think this is fixed. And if not, please provide a minimum (non-working ;) example.

**Comment by matthuszagh** [comment]
I had this issue and updating to the latest master resolved it for me. So, I'd vote to close this.

**Comment by nhatanh-zen8** [comment]
Yeah I think it's fixed too. +1 to close this.
