### ISSUE TITLE
When installing numpy: ELF load command address/offset not properly aligned

### ISSUE THREAD

**Issue by mtn** [DavHau/mach-nix#55]
Just trying this out for the first time with `numpy` as the only requirement and I ran into this error:

```
Python 3.7.6 (default, Dec 18 2019, 19:23:55)
[GCC 9.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
Traceback (most recent call last):
  File "/nix/store/dk7c4hd32212x9ssas5ddbd4xrcj55zh-python3-3.7.6-env/lib/python3.7/site-packages/numpy/core/__init__.py", line 22, in <module>
    from . import multiarray
  File "/nix/store/dk7c4hd32212x9ssas5ddbd4xrcj55zh-python3-3.7.6-env/lib/python3.7/site-packages/numpy/core/multiarray.py", line 12, in <module>
    from . import overrides
  File "/nix/store/dk7c4hd32212x9ssas5ddbd4xrcj55zh-python3-3.7.6-env/lib/python3.7/site-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: libgfortran-2e0d59d6.so.5.0.0: ELF load command address/offset not properly aligned

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nix/store/dk7c4hd32212x9ssas5ddbd4xrcj55zh-python3-3.7.6-env/lib/python3.7/site-packages/numpy/__init__.py", line 140, in <module>
    from . import core
  File "/nix/store/dk7c4hd32212x9ssas5ddbd4xrcj55zh-python3-3.7.6-env/lib/python3.7/site-packages/numpy/core/__init__.py", line 48, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.7 from "/nix/store/dk7c4hd32212x9ssas5ddbd4xrcj55zh-python3-3.7.6-env/bin/python3.7"
  * The NumPy version is: "1.19.0"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: libgfortran-2e0d59d6.so.5.0.0: ELF load command address/offset not properly aligned
```

Here's my `shell.nix`:

```nix
with import <nixpkgs> {};

let
  mach-nix = import (
    builtins.fetchGit {
      url = "https://github.com/DavHau/mach-nix/";
      ref = "2.1.0";
    }
  );

  customPython = mach-nix.mkPython {
    python = pkgs.python37;
    requirements = ''
      numpy
    '';
  };
in

pkgs.mkShell {
  buildInputs = [ customPython ];
}
```

Any tips for investigating this?

**Comment by mtn** [comment]
Oh wait, I think this was just fixed in the new release!

**Comment by mtn** [comment]
It was, closing :)
